### ISSUE TITLE
FPE: helmeos2aux badly defined pgas

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#101]
~~ns_h~~ ns_he step 62 with mesa 14616

When we call helmeos2aux and then call the code in  helm_gammas.dek pgas is 1d-99 thus presinv becomes 1d99 and things overflow.

pgas seems to be set line 1 helm_sum_totals.dek

pgas    = max(pion + pele + ppos + pcoul, 1d-99)

pion =7973870807479.9307
pele = 240143919218957.41
ppos = 0
pcoul = -299391022738062.12

temp_in=627455.24043705384
logtemp_in=5.7975827508311344
den_in=8.4649585047654874, 
logden_in=0.92762483353821545
xfrac=1.0856798434520338e-99
abar_in=55.382502334943794
zbar_in=25.715001077666368, 
coulomb_temp_cut=-9.9999999999999997e+98
coulomb_den_cut=-9.9999999999999997e+98
clip_to_table_boundaries=.TRUE., 
include_radiation=.TRUE.
must_skip_elec_pos=.FALSE.
off_table=.FALSE.

**Comment by adamjermyn** [comment]
Can this be closed now that the FPE fix was merged?
