### ISSUE TITLE
Duplicated interpolation methods.

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#102]
While removing duplicate definitions of `1d0/6d0` I noticed that the same interpolation code is duplicated across the following routines:
```eosde_eva.f90/Do_eosDE_Interpolation```
```eospt_eval.f90/Do_EoS_Interpolations```
```pc_support.f90/Do_Interpolations```
```eosdt_support.f90/Do_EoS_Interpolations```
```weaklib_tables.f90/do_bicubic_interpolations```
```kap_eval_support.f90/Do_Kap_Interpolations```
```ion_tables_eval.f90/Do_ion_Interpolations```

Worse, they all write it in slightly different ways.

Can we extract this interpolation code into a routine that lives in interp2d and just call it from each of the above routines?

**Comment by adamjermyn** [comment]
I agree with @jschwab that this will become a non-issue organically. @warrickball did you make your changes? If so I'm happy to close this.

**Comment by warrickball** [comment]
PR #161, [mentioned earlier in this thread](https://github.com/MESAHub/mesa/issues/102#issuecomment-765538074), merged my tweak in `eos/private/eosdt_support.f90` and it looks like it's still there. The code still matches the diff in that same previous comment.

**Comment by adamjermyn** [comment]
Great! Then I'll call this done and merge. I expect we'll soon remove a few instances and then we have like, two, and it's much less clear that we care about that level of duplication.
