### ISSUE TITLE
Fix dev_ppisn, double_bh, and wind_fed_bhhmxb

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa#160]
These are turned off in main to keep testhub cleaner, but fail on the stale_tests branch, which is up to date with main as of opening this issue.
https://testhub.mesastar.org/stale_tests/commits/acb117e

**Comment by adamjermyn** [comment]
What's the status of this? Are these still release blockers? Has anyone checked if they're still broken on current `main`?

**Comment by evbauer** [comment]
This prodded me to update the `stale_tests` branch, which is just `main` with some extra tests turned on in `do1_test_source1`. Here are the results:
https://testhub.mesastar.org/stale_tests/commits/45fb591

1. Yes, these tests are still broken, and I do think they're release blockers unless @orlox decides otherwise and deletes them.
2. Interestingly, there are two other tests that look like they're running again (`relax_composition_j_entropy` and `extended_convective_penetration`), probably thanks to TDC/MLT updates. I'd like to re-enable those 2 on `main` unless I hear objections.

**Comment by evbauer** [comment]
`dev_high_rot_darkening` is also failing. Do we want to add that to the list in this issue? I don't know whether or not that one should be considered a release blocker.

**Comment by adamjermyn** [comment]
Great, thanks for checking on this! It appears that all of the failures are either compilation failures from `run_star_extras` or inlist reading failures.

Related: @orlox does `dev_to_ppisn_100` serve the same role as `dev_ppisn`? If so we can chuck the latter because the former is passing on `main`...

**Comment by orlox** [comment]
Currently on break till the 26th, but will sort these out/make decisions on whether to keep the week I'm back to work.

dev_to_ppisn_100 does not really fill the same purpose as it does not do the star cutting trick of the ppisn test suite that allows to model long interpulse phases.

**Comment by rjfarmer** [comment]
I've started a branch for fixes for wind_fed_bhhmxb d2044c252

**Comment by orlox** [comment]
wind_fed_bhhmxb and double_bh were already fixed on the test_case_fixes branch. Was trying to sort out all three of these cases in that branch but got stuck on ppisn. Need to bring it up to date with main and merge it, that would just leave ppisn.

**Comment by rjfarmer** [comment]
Okay, looks like you just needed to change some inlist variables to get it to work? There are some fpe's i found while working on wind_fed which we should try and get merged in (mostly to do with initialization of eccentricity related variables)

**Comment by orlox** [comment]
Yes, that's indeed the change. The solver for the mass transfer rate was set to a very high tolerance and that causes the simulation to get stuck at some steps. I just brought the branch up to date with main and checking that the cases still run, if they do I'll do a commit to see if the testhub says anything else broke from the changes. There are a few changes done associated to ppisn fixes that I would like to merge, even if ppisn as a whole is not fixed yet.

**Comment by orlox** [comment]
rsp_load_and_save_file was broken from changes I did to read_model. Reverting those and testing again to see if things work.

**Comment by rjfarmer** [comment]
For the record this is now down to just fixing dev_ppisn.

**Comment by orlox** [comment]
Fixed by pull request #355
