### ISSUE TITLE
Remove string comparison from Skye solid mixing rule.

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#194]
Currently the Skye solid mixing rule is determined by a string comparison used once per call in Skye_coulomb_solid.f90. This could be broken out as a check that happens when the `eos` inlist is read in, and the check could then directly set a function pointer (or an integer flag) to save some cycles.

**Comment by jschwab** [comment]
Yeah, I see the fragility of the string -> integer conversion.

The energy equation option also got implemented as a string for similar reasons as the other controls. 

It would be worth profiling at to double check the impact.  If it is minimal, then I think sticking with strings is worth it from the point of code clarity / simplicity.  I'll try to do that quickly today.

**Comment by adamjermyn** [comment]
Awesome, thank you!

-Adam

**Comment by jschwab** [comment]
Here's the result of profiling the last 7 steps (200 -> 207) of `star/work` in 4dd075b6aa14fa22333ae65beea501286bd7871c.

I'm seeing string stuff at the ~1% level (string trim over by hydro energy and string compare over in Skye).

So this is not absolutely critical, but is probably worth thinking about.  Feels silly to waste time doing the same comparisons over and over gain.

![callgrind out 161233](https://user-images.githubusercontent.com/772632/131878611-fc1c106c-c7cd-45ee-badc-ee72dd5f2274.png)

[callgrind.out.161233.log](https://github.com/MESAHub/mesa/files/7100283/callgrind.out.161233.log)

**Comment by adamjermyn** [comment]
Thanks for doing this! I'm inclined to close the issue. If we ever hit a time where we're spending 10+% of our time on string comparisons we can revisit.

If someone wants to fix this up they can reopen.
