### ISSUE TITLE
Large number of retries in 1M_thermohaline

### ISSUE THREAD

**Issue by jschwab** [MESAHub/mesa#197]
After 6cbc77584ba42b5b812e5b299476b230d7008e42 , the `1M_thermohaline` test went from 1027 steps, 0 retries to 1735 steps, 142 retries.  At present, it is sitting at 1535 steps, 283 retries.

**Comment by adamjermyn** [comment]
This improved somewhat when I turned on TDC for this case, and has stayed a little bit better (now 1764 steps with 154 retries). I'm looking into whether better time-step controls can help further.

**Comment by adamjermyn** [comment]
I believe commit `9ffa01f` [testhub](https://testhub.mesastar.org/TDC_on_default/commits/9ffa01f) resolves this by tightening the `dX` timestep controls.

**Comment by adamjermyn** [comment]
Resolved with PR #293.
