### ISSUE TITLE
Document standalone usage of MESA modules

### ISSUE THREAD

**Issue by jschwab** [MESAHub/mesa#223]
We have a brief description of how to use a MESA module in a standalone mode at:
https://docs.mesastar.org/en/latest/faq.html#how-can-i-use-an-individual-mesa-module

These materials should be incorporated into the docs so that they can become 'living'.

The example code in the source tree should also be cleaned up / modernized.

The example of using the EOS is in `sample/`.
There is also an example of using kap in `kap/test/` (see sample files).  This could potentially move into `sample/`.  (It is not an essential part of the tests.)

Assigning Frank since he wrote the most recent summer school example.

**Comment by adamjermyn** [comment]
Just revisiting this. @fxt44 proposed closing this issue a while ago and it seems reasonable to do so pending a conclusion on the `sample` directory. Is that element of this resolved too? If so can we close?

**Comment by jschwab** [comment]
No, the lingering `sample` issue is why I never closed this.

After looking at the instructions I also wasn't super happy about the fact that this did not remove the dependence on an external resource, it just changed what that external resource is.

**Comment by fxt44** [comment]
essentially the external source provides a highly reduced makefile. i think this is important example for someone who is trying to use a module in an external source code.

**Comment by jschwab** [comment]
I have no problem with the reduced makefile.  Having those exist is great!  My concern about external resources is that future changes in the MESA build system may break the files on Zenodo and no one will notice.

We have a decade-scale baseline demonstrating that unless things loudly complain when they break, they inevitably rot.

**Comment by fxt44** [comment]
ok. feel free to move those stripped makefiles into main, renaming them and placing them where you think best. i'd do it but i'm not yet setup to do a proper pull request.

**Comment by jschwab** [comment]
The main goal was mostly achieved, so I'm closing this.  Things aren't perfect, but they are better than they were.
