### ISSUE TITLE
Document process of setting up new machine with MESA TestHub

### ISSUE THREAD

**Issue by jschwab** [MESAHub/mesa#277]
A good starting point may be Earl's pinned message in Slack.

**Comment by earlbellinger** [comment]
Where do you suggest this to go? Perhaps around https://docs.mesastar.org/en/latest/developing/test_suite.html#mesa-test-hub or elsewhere?

**Comment by jschwab** [comment]
Yeah, that seems fine.  If that page starts getting too unwieldy, we could split out a "MESA Test Hub" page at the same level as "The Test Suite" and cross-reference between them as needed.
