### ISSUE TITLE
Tracking energy from each burn catergory

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#279]
Francisco De Geronimo reported on the mailing list issues with c12_c12 when using sagb_NeNa_MgAl.net. There is an issue here (it reports -99), it seems the fix in the current head has been just to delete most of the burn categories (including c12_c12) from the output. 

I'm leaving this here as a remainder to me to do something about this.

**Comment by adamjermyn** [comment]
I did a lot of those deletions during the crusade on state, as they weren't being set. Happy to see them reverted if those variables will actually have content...

**Comment by rjfarmer** [comment]
That's maybe the confusion as they get set inside net/ and passed back inside s% eps_nuc_categories, which why they probably appeared to be unset.

**Comment by adamjermyn** [comment]
Are they pointers to eps_nuc_categories? Because I looked before deleting
them from star and didn’t see any logic that could set them to anything
other than NaN. (But if they’re pointers I could’ve missed the underlying
array of a different name being set…)

-Adam

**Comment by rjfarmer** [comment]
I can't remember if they where pointers or not. I don't we really need them during a run so I'll just add them back in the history/profile output as indexes from eps_nuc_catergoies rather than needing separate arrays.

**Comment by adamjermyn** [comment]
Sounds like a good solution!

-Adam

**Comment by rjfarmer** [comment]
e5fa9a2b Fixes the output issue though there is still an issue with c12_c12 in cburn_inward
