### ISSUE TITLE
Add back ability to show pgstars during relax operations

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#281]
We lost the disable_pgstar_for_relax option and someone just replaced it with .false. So we can never see a pgstar plot during relaxation phases This is line ~4062 in relax.f90

                if (.false. .and. s% job% pgstar_flag) then
               ! Can't use the star_lib versions otherwise we have a circular dependency in the makefile
               write(*,2) 'after step_loop: call update_pgstar_data', s% model_number
               call update_pgstar_data(s, ierr)
               if (failed()) return
               call do_read_pgstar_controls(s, s% inlist_fname, ierr) 
               if (failed()) return
               call do_pgstar_plots( s, .false., ierr)
               if (failed()) return
            end if

Quick fix is to remove the .false. but we probably want to put back disable_pgstar_for_relax

**Comment by jschwab** [comment]
There is following comment from @bill-paxton , but I don't understand any more of the motivation.

```
commit 74684744aa5c7daefdebeaad25ff0cba9ff76de8
Author: Bill Paxton <paxton@kitp.ucsb.edu>
Date:   Fri Dec 11 01:19:14 2020 +0000

    remove control disable_pgstar_for_relax (what a bad idea that was) [ci skip]
    
    SVN Revision 15166
```
