### ISSUE TITLE
TDC does not allow the carbon flame in `cburn_inward` to make it to the center.

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#291]
This could reflect a bug or a problem in the physics or a problem in our understanding. I certainly don't understand this physics well enough to currently say what's going on. At the moment we're turning TDC off in this case, but I want to make this issue so we don't forget to figure this one out.

**Comment by adamjermyn** [comment]
My next investigation on this was the effect of changing `mixing_length_alpha` down from 1.89 to 1.6. The intuition here is that the flame might be dying because mixing is too efficient at bringing heat out of the flame, so if we can lower the efficiency (by reducing the mixing length) we might get a flame that lasts longer.
![conv_000205](https://user-images.githubusercontent.com/6233759/123975280-3488e380-d98b-11eb-9d3a-6d53d708224b.png)
Indeed this seems to work! I'm going to remove the termination condition next and see if I can run all the way till the flame reaches the center.

**Comment by rjfarmer** [comment]
The classic paper is of course this one: https://ui.adsabs.harvard.edu/abs/2015ApJ...807..184F/abstract and this one is useful for why we shouldn't get mixing ahead of the flame https://ui.adsabs.harvard.edu/abs/2016ApJ...832...71L/abstract 

Not sure anyone done mlt alpha variations in the past. But the past plots you showed the issue is that the carbon flame gets starved of fuel. Carbon flames move though conduction and it you mix  carbon in from beyond the bottom of the flame then as the flame moves downwards it enters a carbon poor region and dies.

**Comment by adamjermyn** [comment]
Ah I see. So that's what happens just after model 210 here: the CZ extends below the flame, mixing carbon up into the flame and preventing it from moving lower.
![conv_000240](https://user-images.githubusercontent.com/6233759/123979661-eece1a00-d98e-11eb-9c54-56900b046f08.png)

So the concrete question to answer is: Why does TDC mix below the flame? That's something I can look into.

**Comment by adamjermyn** [comment]
This feature is sensitive to `dt`. If I push `dt` down I get different mixing features below the flame. That suggests this isn't resolved. I'm running with tighter controls now.

**Comment by adamjermyn** [comment]
With tighter timestep controls we can eliminate the bottom convective mixing. What's left is pure overshooting, which eventually kills the flame:
![conv_000380](https://user-images.githubusercontent.com/6233759/123990391-b717a000-d997-11eb-896f-0cc58d63381d.png)

Running with overshooting off below CZ's next...

**Comment by adamjermyn** [comment]
If you run without bottom overshooting you get much nicer curves and the flame keeps going (still running). It just takes a while:
![conv_000860](https://user-images.githubusercontent.com/6233759/123999725-d0711a00-d9a0-11eb-94d2-01178742dafd.png)

The abundances look much nicer too:
<img width="778" alt="Screen Shot 2021-06-30 at 12 44 20 PM" src="https://user-images.githubusercontent.com/6233759/123999818-e8489e00-d9a0-11eb-9894-0301cd5f693d.png">

So I think we just don't want undershooting here? That would also make sense physically (it's an extremely stiff boundary so it'd be shocking if you had substantial convective undershoot).

**Comment by rjfarmer** [comment]
Yes the reason i added undershoot was it makes the run quicker. I was less concerned with where the flame dies (at that depends on the mixing) and more concerned with that large extra convection zone below the flame tdc created. If that convection zone disappears, just at higher resolution, then that's fine and we can turn tdc on.

**Comment by adamjermyn** [comment]
Yes that convection zone disappears when you get rid of undershoot.

**Comment by adamjermyn** [comment]
I'm just going to let this run till the flame dies though and see what that looks like.

**Comment by adamjermyn** [comment]
Also we definitely want TDC here (physically)...
<img width="217" alt="Screen Shot 2021-06-30 at 1 05 30 PM" src="https://user-images.githubusercontent.com/6233759/124002554-e46a4b00-d9a3-11eb-9f88-7cc152d80b94.png">

**Comment by adamjermyn** [comment]
@jschwab  and I had a call today to talk a bit about this. He had the suggestion to add thermohaline mixing, because some of the ill-behavior in these runs was coming from the lower boundary becoming first thermohaline unstable and then Ledoux unstable (whereas physically it should just mix via thermohaline before then).

Thermohaline acts a bit like undershooting in accelerating the evolution, but is much more well-behaved numerically, and doesn't kill the flame. I'm inclined to keep this on...

![grid_000990](https://user-images.githubusercontent.com/6233759/124190655-a565f380-da90-11eb-9065-1e96086521f2.png)
![conv_001095](https://user-images.githubusercontent.com/6233759/124190699-b57dd300-da90-11eb-846e-7a354f9f7ca9.png)

**Comment by adamjermyn** [comment]
And it's passing! I'm closing this one out. Feel free to reopen if there's more you want to discuss.

**Comment by adamjermyn** [comment]
One last thing. At @jschwab 's suggestion I let this one run for a longer time (with the termination condition disabled). The flame doesn't quite make it to the center (see below), but I think that's just because thermohaline does a lot of mixing along the way.
![conv_002000](https://user-images.githubusercontent.com/6233759/124289300-27512d80-db20-11eb-8739-7d9ad2a193b6.png)
![grid_002000](https://user-images.githubusercontent.com/6233759/124289446-56679f00-db20-11eb-9bc6-e68cf213667a.png)
For what it's worth the thermohaline prescription I'm using is one that's calibrated to reproduce ascending RGB Li abundances, so it's not totally crazy...
