### ISSUE TITLE
Fix RSP fpe's

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#299]
They've existed for long enough now we should go and actually fix them and stop ignoring the problem

Current failures (cross out as they get fixed):

- rsp_BEP
- rsp_BLAP
- rsp_cepheid
- rsp_delta_scuti
- rsp_rr_lyrae
- rsp_type_II_cepheid
- rsp_check_2nd_crossing
- rsp_gyre
- rsp_save_and_load_file

**Comment by rjfarmer** [comment]
rsp_cepheid line 973 of rsp_lina.f90:

         if((WIx(I).lt.MINI) &
               .and.(P4*WRx(I)/WIx(I).gt.-.3d+1) &
               .and.(WIx(I).gt.1.d-9))then

Breaks when WIx(I)==0. The comments suggest we are searching for the smallest positive number so i don't know why we don't do a simple if >0 and <smallest found value if statement? @rsmolec

**Comment by rsmolec** [comment]
As in a line above, that is commented out, the second condition was dropped, I guess it is fact needed. There are two magic numbers here, which suggests that I chose them based on lots of experimenting and problems faced when they were not there; unfortunately I don't remember the details now. The second line is essentially condition on growth rate.  We should never hit WIx(I)=0 for non-adiabtic case considered here. Is shifting a third condition to external if, which then protects from WIx==0 case, a solution?

**Comment by rjfarmer** [comment]
Sure we if we switch to:

     if((WIx(I).lt.MINI) .and.(WIx(I).gt.1.d-9))then
        if(P4*WRx(I)/WIx(I).gt.-.3d+1)then

That should protect from WIx(I)=0
