### ISSUE TITLE
get_stable_mass_frac does not handle multiple decay pathways

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#303]
get_stable_mass_frac is meant to take the current net's isotope list and "decay" the composition to itsstable isotopes (i.e assume some long timescale and let all the weak decays happen). This is based on Frank's decay.zip code which I added to MESA. There are however some problems I've found recently:

- It doesn't handle cases when an isotope may decay in more than one way (I stumbled over co64 with Wikipedia tells me has both has beta+ and - decays (60/40%))
- Not every unstable isotope gets assigned a stable one (i think this is happening when you can have both proton and neutron rich isotopes decay to a stable iso, we only track one of the pathways). I ran into this with cu64, co58, mn54, b8, sc46, cl36, sc48 

So I need to work out if I can fix it, remove it, or ignore the problem. It would be nice to have a quick way to turn radioactive isotopes into stable ones, but maybe we should be doing this in a proper network calculation and not in a quick-and-dirty manner as we do now.

**Comment by fxt44** [comment]
co64 has only one decay mode to stable ni64. see, for example, http://nucleardata.nuclear.lu.se/toi/nuclide.asp?iZA=270064 . loading a co64 mass fraction of 1.0, the decay code yields a ni64 mass fraction of 1.0. i'll try some of the other isotopes mentioned in a bit.

**Comment by fxt44** [comment]
i see now you probably meant cu64, not co64. the decay source code is an approximation - no branching ratios, infinite timescale, etc. this said, it should account for every isotope. i checked it with a 497 composition vector and the following isotopes were not accounted for

 unaccounted   b8   
 unaccounted cl36 
 unaccounted sc46 
 unaccounted sc48 
 unaccounted mn54 
 unaccounted co58 
 unaccounted cu64 
 unaccounted ga70 
 unaccounted as74 
 unaccounted as76 
 unaccounted br78 
 unaccounted br80 
 unaccounted br82 
 unaccounted rb84 

which matches your list plus a few more.  you are correct that the issue is any stable isotope (currently) can only have proton rich progenitors of neutron rich progenitors or made as itself, but not both. the isotopes above have contributions from both, usually just one on the side not being counted. so what to do? options include a new or different jcode(i) value - which would need lots of testing - or a hand-coding that addresses the dozen or so isotopes in the list above.

**Comment by fxt44** [comment]
this snippet does the special cases and alerts for unknown special cases.

```
! for every isotope in the input composition
      do i=1,nin
       ifound = 0

! for every isotope in the solar composition
       do j=1,solsiz

! special case of b8 to alphas
        if (namin(i) .eq. 'b8   ' .and. namout(j) .eq. 'he4  ') then
         xout(j) = xout(j) + xin(i)
         ifound = 1
         exit
        end if

! main loop over equal number of nucleons A
        if (na(i) .ne. iasol(j)) cycle
!        write(6,'(3i4,a6,3i4,a6,i4)') i, na(i), nz(i), namin(i), j, iasol(j), izsol(j), namout(j), jcode(j)
        if (                       (jcode(j) .eq. 0)  .or. &
             (nz(i).ge.izsol(j) .and. jcode(j).eq.1)  .or. &
             (nz(i).le.izsol(j) .and. jcode(j).eq.2)  .or. &
             (nz(i).eq.izsol(j) .and. jcode(j).eq.3)  .or. &
             (namin(i) .eq. 'cl36 ' .and. namout(j) .eq. 'ar36 ')  .or. & ! cl36 special case
             (namin(i) .eq. 'sc46 ' .and. namout(j) .eq. 'ti46 ')  .or. & ! sc46 special case
             (namin(i) .eq. 'sc48 ' .and. namout(j) .eq. 'ti48 ')  .or. & ! sc48 special case
             (namin(i) .eq. 'mn54 ' .and. namout(j) .eq. 'cr54 ')  .or. & ! mn54 special case
             (namin(i) .eq. 'co58 ' .and. namout(j) .eq. 'fe58 ')  .or. & ! co58 special case
             (namin(i) .eq. 'cu64 ' .and. namout(j) .eq. 'ni64 ')  .or. & ! cu64 special case
             (namin(i) .eq. 'ga70 ' .and. namout(j) .eq. 'ge70 ')  .or. & ! ga70 special case
             (namin(i) .eq. 'as74 ' .and. namout(j) .eq. 'ge74 ')  .or. & ! as74 special case
             (namin(i) .eq. 'as76 ' .and. namout(j) .eq. 'se76 ')  .or. & ! as76 special case
             (namin(i) .eq. 'br78 ' .and. namout(j) .eq. 'se78 ')  .or. & ! br78 special case
             (namin(i) .eq. 'br80 ' .and. namout(j) .eq. 'kr80 ')  .or. & ! br80 special case
             (namin(i) .eq. 'br82 ' .and. namout(j) .eq. 'kr82 ')  .or. & ! br82 special case
             (namin(i) .eq. 'rb84 ' .and. namout(j) .eq. 'kr84 ')       & ! rb84 special case
             ) then
         xout(j) = xout(j) + xin(i)
         ifound = 1
         exit
        end if
       enddo

! if we are here, we have an isotope that cannot be placed
       if (ifound .eq. 0)  write(6,*) 'unaccounted for: ',i, na(i), nz(i), namin(i)
      enddo

```

**Comment by rjfarmer** [comment]
Thanks for checking. I was getting worried as I stumbled over 7 missing isotopes that there where going to be many more missing ones. But it looks like i just got unlucky with my choice of net. Hard coding it is probably the best bet (until we get round to running the 3335 net :) ).

As for the branching, I should just add some comments for whats going on so people realize what we are doing so they can decide if it is or not a problem for them.

**Comment by fxt44** [comment]
fair enough on the comments. most of the special cases involve a single neutron rich isotope, whereas most of the flows (jcode) are on the proton-rich side. other assumptions are the neglect of  theoretically possible double beta decays (stable isotope -> stable isotope), that the proton is stable, and  in accord with common astro practice that isotopes like k40 are considered stable.
