### ISSUE TITLE
conv_vel equation should be updated to use auto_diff or removed

### ISSUE THREAD

**Issue by jschwab** [MESAHub/mesa#308]
The `conv_vel` machinery needs to be updated to use auto_diff or removed.  This choice might depend on the status of TDC.

https://github.com/MESAHub/mesa/blob/6c6bcee969b11b66f0142bac3f8cefb2fab93a0a/star/private/hydro_eqns.f90#L617
https://github.com/MESAHub/mesa/blob/6c6bcee969b11b66f0142bac3f8cefb2fab93a0a/star/private/struct_burn_mix.f90#L509

**Comment by adamjermyn** [comment]
All of the issues in TDC that I'm aware of have now been fixed, so it'd be good to see if it resolves the problem cases that `conv_vel` is meant to solve. Could someone point me to one so I can try it? The only thing I'm aware of on r15140 is that it's super hard to get through the helium flash without `conv_vel`.

**Comment by orlox** [comment]
within the test_suite I think ppisn is really what depends on it. I have seen conv_vel help with the helium flash as well as massive star evolution past carbon burning, but none of that is part of the test_suite as far as I remember.

Still cant get ppisn to work but at this point I'm not sure the issues are really on TDC but rather ppisn being ppisn (mostly issues with the outermost cells of the model). In the test_case_fixes branch ppisn can start but it does not run to completion yet.

**Comment by adamjermyn** [comment]
Ok. I mean the various core collapse cases definitely make use of TDC (and see changed outcomes because of it)...

**Comment by rjfarmer** [comment]
This closable now after #342 ?

**Comment by orlox** [comment]
After there is an all-green from the test suite on main, just to be sure.

**Comment by evbauer** [comment]
Oops, Cannon picked up the [ci fpe] stuff from the squashed commit history. I pushed another commit so hopefully we get a clean test on that one. At least we'll know exactly where we stand on fpe's now.

**Comment by rjfarmer** [comment]
Testing is all green https://testhub.mesastar.org/main/commits/0a93dd3
