### ISSUE TITLE
Question in eval_super_eddington_wind

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#320]
There's a comment in `eval_super_eddington_wind` in the comments on line 631:
```
         vesc2 = s% cgrav(1)*M/R  ! GM/R vs. 2GM/R ?
```

So which do we want, 1 or 2?

**Comment by fxt44** [comment]
1/2 m v*2 = GMm/R

where the right hand side is the work done against the gravitational attraction to take the mass from the surface to infinity. thus the standard definition of the escape speed 

v_esc^2 = 2 GM/R

has a factor of two from definition of the kinetic energy.

the orbital speed of a small body in a circular orbit is

v_orbit^2 = GM/r

which is maybe where the comment comes from. so the orbital and escape speed are related by

v_orbit = v_escape / sqrt(2)

which is fun to contemplate.

ok?

**Comment by adamjermyn** [comment]
Agreed! But which do we want to be using, the escape speed or the orbital speed? The way I see it we have a few choices:
1. Rename the variable to `vorb2` and leave the actual math as-is.
2. Change the math to pick up a factor of `2` and hope Testhub smiles upon us.

Any preferences?

**Comment by fxt44** [comment]
ok. let me revisit the routine to glean the intention of the speed.

**Comment by fxt44** [comment]
for a wind the escape speed appropriate. but, there appears to be more going on. 

timescale = E/L, with E being an energy in erg and L being the luminosity in erg/s. 
so, mdot = L/e where e is a specific energy E/m. if all the energy is kinetic, then E/m = v^2/2. 
thus mdot = L/(v^2/2), and for material leaving at the escape speed (the ddington limit) 
this becomes mdot_edd = L(v_esc^2/2).

as a verification of sorts, owocki in a series of articles in the mid 2000's consistently uses mdot_edd = L(v_esc^2/2),
for example equation 20 in https://ui.adsabs.harvard.edu/abs/2004ApJ...616..525O/abstract .

so i am leaning toward leaving vesc2 in the source code as it stands, with a coefficient of 1,
but adding a more extended comment on where it comes from.

all good?

**Comment by adamjermyn** [comment]
How about if we defined vesc2 to be 2GM/R, but then put another `2` in the
`mdot` expression to cancel it. It's extra operations but I think for
clarity on such a cheap routine we can pay that cost...

-Adam

**Comment by fxt44** [comment]
fine by me. maybe multiple by 0.5 to save a division.
