### ISSUE TITLE
FPE in skye_thermodynamics when xnefer is 1d-99

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#337]
https://github.com/MESAHub/mesa/blob/45c53d042d87dd454450a3fc15f9b8d80f5d2b24/eos/private/skye_thermodynamics.f90#L136

This is causing fpe's in 16_conv_premix and looks like a number of other test cases as well (including 1M_pre_ms_to_wd).

https://testhub.mesastar.org/main/commits/86b93de/test_cases/star/16M_conv_premix

16_conv_premix has xnefer=1d-99 (looks like is coming from ideal_eos) which is then divided by avo and density becoming ~3d-117.

Then we hit:

https://github.com/MESAHub/mesa/blob/45c53d042d87dd454450a3fc15f9b8d80f5d2b24/auto_diff/private/auto_diff_real_2var_order3_module.f90#L959

which does (3d-117) ** 3 which becomes 0. Then we try to do 1/0 in powm1.

So should powm1 get error handling for x==0? 
Should skye do something different when xnefer is very small?

**Comment by adamjermyn** [comment]
Commit dcb7c48c..ae373f6f might resolve this...

-Adam

**Comment by evbauer** [comment]
Looks like that fixed 11 fpe's! I still see at least one more Skye/ideal related fpe here:
https://logs.mesastar.org/4afa315d2f1989beaca621aeaa5fc3f03f3178d2/cannon_conroy_intel/20M_pre_ms_to_core_collapse/err.txt
But overall it looks much better.

**Comment by adamjermyn** [comment]
Great! So can we close this one?
