### ISSUE TITLE
Autodiff updates

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#341]
Some thoughts on auto_diff for use in run_star_extras.f90:

- I think we need to add `use auto_diff` as a standard import in all the run_star_extras/other hook files otherwise i get this error: 
````
  553 |       s% extra_heat(:) = 1d-99
      |                         1
Error: Cannot convert REAL(8) to TYPE(auto_diff_real_star_order1) at (1)
````
I can go through and do that, unless I'm missing something?

- Any objection to making the functions/subroutines elemental? That should mean people can make arrays of autodiff types and things just work.

- We currently have a assign_from_real_dp and assign_from_int for doing autodiff = real(dp) but could we get the flipped version for doing real(dp) = autodiff? So people don't need to do the autodiff%val just to get the value?

````
elemental subroutine real_dp_from_autodiff(var, diff)
      real(dp), intent(out) :: var
      type(auto_diff_real_star_order1), intent(in) :: diff
      var = diff%var
   end subroutine real_dp_from_autodiff
````

Note we need to name the arguments differently to that used in assign_from_real_dp (http://www.cs.rpi.edu/~szymansk/OOF90/bugs.html#10)

**Comment by orlox** [comment]
At least for me not having real(dp) = autodiff worked as a feature. It prevented me from having parts of the code erase all the autodiff information in a way that would be tough to track.

**Comment by rjfarmer** [comment]
Well we either need real(dp) = autodiff or we need more documentation on autodiff as users are going to hit this when they upgrade their run_star_extras (i hit this when using other_energy) and they get these weird looking error messages when trying to assign, say an element of extra_heat, to a local variable.

We a page on autodiff https://docs.mesastar.org/en/latest/auto_diff/overview.html but we would probably want to get this linked in more places (i'm imagining all the user questions we will get)

**Comment by adamjermyn** [comment]
The absence of `real(dp) = autodiff` is a feature, not a bug :-). We had a long thread on this before we moved over to GitHub, but the summary is exactly what Pablo said: this is to prevent users/developers from accidentally erasing derivative information halfway through a calculation.

What would help to have in the docs? I'm happy to write some...

**Comment by rjfarmer** [comment]
>What would help to have in the docs? I'm happy to write some...

Maybe a worked example of a hook. Putting data into a autodiff type, manipulating the array, printing the value back out/assigning to a real etc. Bonus points if it also shows the common errors and their messages (not having the use statement, trying to do real = autodiff) so that people can search for their error message.

**Comment by adamjermyn** [comment]
I've taken a first pass at this on `main`. Let me know what you think.
