### ISSUE TITLE
Make history/profile columns case insenstive

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#344]
Turns out it matters if you put capitals in the names or not. It would be better if it did not matter whether you had the right capitalization.

**Comment by fxt44** [comment]
to the extent these might be useful in some way:


      subroutine caseup(string)
      implicit none
!
! this routine converts an ascii string to all upper case.
!
! declare
      character*(*)  string
      integer        i,x,smalla,smallz,change
      parameter     (smalla = 97,  smallz = 122,  change = 32)

      do i=1,len(string)
       x = ichar( string(i:i) )
       if (x .ge. smalla  .and.  x .le. smallz ) then
        x           = x - change
        string(i:i) = char(x)
       end if
      enddo
      return
      end





      subroutine casedn(string)
      implicit none
!
! this routine converts an ascii string to all lower case.
!
! declare
      character*(*)  string
      integer        i,x,biga,bigz,change
      parameter     (biga = 65, bigz = 90, change = 32)

      do i=1,len(string)
       x = ichar(string(i:i))
       if (x .ge. biga  .and.  x .le. bigz ) then
        x           = x + change
        string(i:i) = char(x)
       end if
      enddo
      return
      end


there are, of course, other ways to achieve case conversion.

**Comment by warrickball** [comment]
`utils_lib` also has `StrUpCase` and `StrLowCase` subroutines:
https://github.com/MESAHub/mesa/blob/a59ab7317b151497c8a3a2a0f4bd67327d84ddf6/utils/public/utils_lib.f90#L892-L914
