### ISSUE TITLE
Should set_tdc call mesa_error?

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#349]
I'm running a model with tdc on and hitting a ierr/=0 in get_TDC_solution, which then gets repeated with reporting on.

My question is should we call mesa_error here and stop the run when we first hit this? Otherwise i'm getting lots of debug info printed to screen (i guess for every zone?) Is it helpful to repeat the error a thousand times or can we stop after just one?

**Comment by rjfarmer** [comment]
Thinking about it, it would be better in star/private/turb_support.f90. Which i just noticed doesn't actually check the return ierr from set_tdc or any of the set_ functions. 

I can go through and add the error handling if you agree adam?

**Comment by adamjermyn** [comment]
Yes please do!

-Adam

**Comment by rjfarmer** [comment]
Added in df873a92
