### ISSUE TITLE
Incomplete documentation regarding removal of ionization module in the release candidate r21.12.1-rc1

### ISSUE THREAD

**Issue by mathren** [MESAHub/mesa#350]
In the [changelog](https://docs.mesastar.org/en/latest/changelog.html) for the release candidate, there is the following line under "other changes":

```The ionization module has been removed.```

This is not very informative for the end-users on what they should do if they were using this module (say to calculate internal energy accounting for ionization potentials).

**Comment by evbauer** [comment]
Thanks Mathieu. I can try to add some more detail on this.

Would it be possible for you to point me to a particular use case that could benefit from more documentation about this change? One of the reasons the ionization module was removed is that most of it didn't actually get used internally in MESA itself, and lots of it was based on unpublished and mostly untested code.

**Comment by mathren** [comment]
I have not used or tested this so much. I inherited some run_star_extras.f90 which were using `eval_ionization`. I think the aim is to have a profile of the ionization of elements, which is relevant for common envelope calculations.
I am not stopped by this personally, as I was not really using that, so I can continue testing just commenting out that stuff from my runs, but I suppose other users might encounter this. Possibly, @aarondotter may want to chime in.

**Comment by evbauer** [comment]
Can you take a look at the updated [changelog entry](https://docs.mesastar.org/en/latest/changelog.html#other-changes)? Does that look sufficient?

**Comment by evbauer** [comment]
Thank you! These are really helpful comments.

I suppose we might still get some wailing and gnashing of teeth when `eval_ionization` disappears, but at least we have some documentation now that should help people realize they shouldn't have been relying on it...
