### ISSUE TITLE
Cannot match namelist object name surf_w_div_w_crit_limit

### ISSUE THREAD

**Issue by mathren** [MESAHub/mesa#351]
Hi, I am trying to adapt my setup from [here](https://zenodo.org/record/4701565) to test it with the release candidate.
The changelog does not seem to mention `surf_w_div_w_crit_limit` or anything about the implicit wind calculation when a star is close to critical rotation. Not sure what to do to translate to the release candidate and test my models.

**Comment by rjfarmer** [comment]
It seems to have been renamed to surf_omega_div_omega_crit_limit in 60d709fff

I'll update the docs
