### ISSUE TITLE
Clean up user supplied integer history columns

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#354]
Currently we have this hack https://github.com/MESAHub/mesa/blob/5638971ddd3c35418d2b70610fcde993a245cbb9/star/private/history.f90#L476 for determining if a user history column should be a int or double.  This fails if you pass a value larger than huge(int)

After the release we should clean this up and just pass an extra is_int array to data_for_extra_history_columns to let a user flag if it should be an int or double. 

For now i'm just going to add this:

````fortran
         else if (pass == 3) then
               if (abs(extra_col_vals(j)) < huge(int_val))then 
                  int_val = int(extra_col_vals(j))
                  if (abs(extra_col_vals(j) - dble(int_val)) < &
                        1d-10*max(1d-10,abs(extra_col_vals(j)))) then
                     call do_int_val(j + col_offset, int_val)
                  else
                     call do_val(j + col_offset, extra_col_vals(j))
                  end if
               else
                  call do_val(j + col_offset, extra_col_vals(j))
               end if
            end if
````

So we don't call int(val) when larger than huge(int)

**Comment by warrickball** [comment]
I always presumed extra column data could only be floats. I didn't realise we tried to detect whether or not extra data are ints or floats. I guess we could adjust the logic from testing `x-int(x)` to instead testing the residual of  something like `x-modulo(x, 1.0_dp)`, then casting `x` as an integer if necessary, but I feel like this is prone to accidentally turning a `float` into an `int` (e.g. if the user is recording some sort of fraction that often takes limiting values of 0 or 1) so your suggestion is better anyway.

**Comment by rjfarmer** [comment]
I also didn't realise we tried. But ppisn tries to output a large float which fpe's here.
