### ISSUE TITLE
RSP may be broken in r21.12.1

### ISSUE THREAD

**Issue by rsmolec** [MESAHub/mesa#396]
When computing the same model (same inlist; just with necessary differences regarding eos) with two public release versions 15140 and r21.12.1 we get different results in nonlinear model. Linear results (content of LINA_period_and_growth.data) are the same. Also, models integrated with small velocity kick, like 0.1 km/s look consistent, at least for first cycles of integration. However for a large velocity kick, like 10km/s, results are differnt right from the beginning. The issue may be reproduced with a standard test_suite rsp_Cepheid case. r.21.12.1 likely has an issue. This may be demonstrated with another inlist, see below (test provided by Vincent Hocde). For this model only F mode is linearly unstable and strongly driven. In 15140 we can see a nice growth of oscillation amplitude and convergence to limit cycle. With r21.12.1, despite the same linear results, oscillations decay.
`
&star_job

      show_log_description_at_start = .false.

      create_RSP_model = .true.

      save_model_when_terminate = .true.
      save_model_filename = 'final.mod'

      initial_zfracs = 6

      ! History and profile columns 
      !history_columns_file = 'history_columns.list'
      !profile_columns_file = 'profile_columns.list'

      !color_num_files=2
      !color_file_names(2)='blackbody_johnson.dat'
      !color_num_colors(2)=5

      ! Default file from Lejeune, Cuisinier, Buser (1998) A&AS 130, 65-75
      ! Can be replaced if need be.
      ! The filter names are U B V R I J H K L Lprime M (case sensitive)

      ! ::

      color_num_files = 1  
      color_file_names(1) = 'lcb98cor.dat'
      color_num_colors(1) = 11

      set_initial_age = .true.
      initial_age = 0

      set_initial_model_number = .true.
      initial_model_number = 0
      
      set_initial_cumulative_energy_error = .true.
      new_cumulative_energy_error = 0d0
      
      pgstar_flag = .false.
   
/ ! end of star_job namelist

&eos
/ ! end of eos namelist

&kap
   Zbase = 0.014

      kap_file_prefix = 'a09'
      kap_lowT_prefix = 'lowT_fa05_a09p'
      kap_CO_prefix = 'a09_co'

/ ! end of kap namelist

&controls

   ! limit max_model_number as part of test_suite
!max_model_number = 2
 RSP_max_num_periods = 1000

! RSP controls

   !x_integer_ctrl(1) = 10 ! which period to check
   !x_ctrl(1) = 3.92305d0 ! expected period (in days) 

  
   RSP_mass = 3
   RSP_Teff = 5800
   RSP_L = 4638

   RSP_X = 0.70668!
   RSP_Z = 0.014!

   !RSP_Qvisc_quadratic = 2.0d0
   !RSP_zsh = 0.01d0
   !RSP_cq = 1.0d0
      
   ! Parameters of the convection model.
   ! Note that RSP_alfap, RSP_alfas, RSP_alfac, RSP_alfad and RSP_gammar
   ! are expressed in the units of standard values.
   ! Standard values are the ones for which static version of the Kuhfuss
   ! model reduces to standard MLT.
   ! See Table 1 in Smolec & Moskalik 2008
   ! http://adsabs.harvard.edu/abs/2008AcA....58..193S
   ! for standard values and the description of the parameters.
   ! Set A 
   RSP_alfa =      1.5d0         ! mixing length; alfa = 0 gives a purely radiative model.
   RSP_alfac =     1.0d0         ! convective flux; Lc ~ RSP_alfac
   RSP_alfas =     1.0d0         ! turbulent source; Lc ~ 1/ALFAS; PII ~ RSP_alfas
   RSP_alfad =     1.0d0         ! turbulent dissipation; damp ~ RSP_alfad
   RSP_alfap =     0.0d0         ! turbulent pressure; Pt ~ alfap     
   RSP_alfat =     0.0d0         ! turbulent flux; Lt ~ RSP_alfat; overshooting.
   RSP_alfam =     0.25d0        ! eddy viscosity; Chi & Eq ~ RSP_alfam
   RSP_gammar =    0.0d0         ! radiative losses; dampR ~ RSP_gammar  

   ! Set D 
   !RSP_alfa =      1.5d0         ! mixing length; alfa = 0 gives a purely radiative model.
   !RSP_alfac =     1.0d0         ! convective flux; Lc ~ RSP_alfac
   !RSP_alfas =     1.0d0         ! turbulent source; Lc ~ 1/ALFAS; PII ~ RSP_alfas
   !RSP_alfad =     1.0d0         ! turbulent dissipation; damp ~ RSP_alfad
   !RSP_alfap =     1.0d0         ! turbulent pressure; Pt ~ alfap     
   !RSP_alfat =     0.01d0         ! turbulent flux; Lt ~ RSP_alfat; overshooting.
   !RSP_alfam =     0.70d0        ! eddy viscosity; Chi & Eq ~ RSP_alfam
   !RSP_gammar =    1.0d0         ! radiative losses; dampR ~ RSP_gammar  

      ! Initial kick makes use of the scaled linear velocity eigenvector
      ! of a given mode or of the linear combination of the eigenvectors
      ! for the fundamental mode and first two radial overtones.
      ! The surface velocity is set to RSP_kick_vsurf_km_per_sec and
      ! the mode content is set by RSP_fraction_1st_overtone and RSP_fraction_2nd_overtone
   RSP_nmodes = 12
   RSP_kick_vsurf_km_per_sec = 10d0
   RSP_fraction_1st_overtone = 0d0
   !RSP_fraction_2nd_overtone = 0d0

   ! fraction from fundamental = 1d0 - (1st + 2nd)
   ! Note: This is important for models in which two or more modes are linearly unstable.
   ! Appropriate setting may help to arrive at the desired mode, since the final pulsation
   ! state may depend on initial conditions set by the three parameters above.
   ! Integration of the same model with different initial kicks is a way to study
   ! the nonlinear mode selection -
   ! for an example see Fig. 1 in Smolec & Moskalik 2010
   ! http://adsabs.harvard.edu/abs/2010A%26A...524A..40S .

! output controls
   
      terminal_show_age_units = 'days'

      !num_trace_history_values = 2
      trace_history_value_name(1) = 'rel_E_err'
      trace_history_value_name(2) = 'log_rel_run_E_err'

   ! for cases in which you have a run that has reached steady pulses
   ! and you want to look at plots of just a few periods to see the details,
   ! i suggest the following method. interrupt the run soon after
   ! it makes a photo.  remove or delete LOGS/history.data to force
   ! creation of a new one when restart.  edit the inlist to set
   ! history_interval to 1 to get maximum time resolution.  
   ! restart the run and let it go for as many periods as desired.   
         !RSP_work_period = 5
         RSP_work_filename = 'work.data'

      photo_interval = 1000
      profile_interval = 4000
      history_interval = 10
      terminal_interval = 4000

      ! output data for 3d map.  format same as for gnuplot pm3d      ! ::   
    RSP_write_map = .false.
    RSP_map_columns_filename = 'map_columns.list'      ! items listed in your map columns must also appear in your profile columns      ! ::    
    RSP_map_filename = 'map.data'
    RSP_map_first_period =999
    RSP_map_last_period = 1000
    RSP_map_zone_interval = 2
    RSP_map_history_filename = 'map_history.data'

/ ! end of controls namelist

&pgstar

      !pause = .true.

      !pgstar_interval = 20
         
      Grid2_win_flag = .true.

      Grid2_title = '7.0 M\d\(2281)\u  Z=0.007  Y Oph'
      
      History_Panels1_xaxis_name='star_age_day'
      History_Panels1_max_width = 365 ! only used if > 0.  causes xmin to move with xmax.

      ! Grid2_file_flag = .true.
      file_digits = 7
      Grid2_file_dir = 'png'
      Grid2_file_prefix = 'grid'
      Grid2_file_interval = 5 ! output when mod(model_number,Grid2_file_interval)==0
      
      !Profile_Panels1_show_grid = .true.

      Profile_Panels1_xaxis_name = 'logtau'
      Profile_Panels1_xaxis_reversed = .true.
      Profile_Panels1_xmin = -101D0
      Profile_Panels1_xmax = -101D0

      Profile_Panels1_dymin(4) = 0.02
      Profile_Panels1_yaxis_name(2) = 'avg_charge_He'         

/ ! end of pgstar namelist
`

**Comment by adamjermyn** [comment]
RSP was largely untouched in a lot of the work between 15140 and r21.12.1, so that's a bit disconcerting. For instance RSP has its own version of TDC, so shouldn't care about the MLT/TDC work. Likewise RSP doesn't use auto_diff and has its own solver, so none of the work there should make a difference to RSP.

The things that have changed that RSP should know about are the EOS and opacities. There's been a lot of work on both, and it seems very plausible something there has changed.

On the EOS side we introduced Skye and turned it on by default. There was also a switch from OPAL -> FreeEOS, though that might have already happened as of 15140?

I haven't followed the opacity side, but maybe someone else can comment?

**Comment by rsmolec** [comment]
A solution, or a fix, that makes RSP reproducing the results of 15140 is to include `RSP_do_check_omega = .true.` as default.
