### ISSUE TITLE
Bug adding history_columns.list to default work directory 

### ISSUE THREAD

**Issue by aurimontem** [MESAHub/mesa#404]
Hi MESA devs! 

When creating a new history_columns.list file in a star/work directory which contains the line

include '' 

as recommended for when you don't want to copy the entire defaults file, the work directory won't run and instead displays the error message: 

 All this and more are saved in the LOGS directory during the run.
 create pre-main-sequence model
                                          species  mass           8    1.5000000000000002D+01

                                        relax_num_steps         300

 too many levels of nesting for log column files          21
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed for included log columns list
 failed in relax num steps
 failed in do_relax_num_steps
 star_create_pre_ms_model ierr          -1
 do_load1_star ierr          -1
 do_before_evolve_loop ierr          -1
 do_before_evolve_loop ierr          -1

This message is generated in $MESA_DIR/star/private/history_spec.f90 (lines 150-162).

The bug only occurs using $MESA_DIR/star/work or a clone in another directory, but does not appear in the test_suite cases we checked. That is, in (e.g.) $MESA_DIR/star/test_suite/make_zams, creating a history_columns.list file in the directory which only contains  include ''  will not cause an error; MESA runs fine and LOGS files are generated as expected. 

The bug also only occurs when using the latest MESA SDK, and using MESA r21.12.1 compiled with old versions of the SDK ran as expected with no problems. 

Will Schultz, Sunny Wong, and Phys232 students at UCSB ran into this problem in the context of MESA homework in Stars with Lars.

**Comment by rjfarmer** [comment]
You know I never realized we could do that.

Looking at the code i don't think it should be working with old SDK's, nor should it have worked since before 15140, given we barely made any changes to history_specs.f90 since the github migration.

Anyway thanks for reporting this, fix coming shortly.
