### ISSUE TITLE
star_info structure

### ISSUE THREAD

**Issue by Anohita1** [MESAHub/mesa#430]
screening_mode, s% theta_e(k), &
Error: 'theta_e'  is not a member of the 'star_info' structure
make: *** [/path/mesa-r22.05.1/star/work_standard_makefile:39: run_star_extras.o]

Fails to compile run_star_extras.f90

**Comment by rjfarmer** [comment]
This is normally not enough information to answer a question. See https://docs.mesastar.org/en/release-r22.05.1/installation.html#post-a-question-to-mesa-users on how to ask a good question.

That said I suggest when moving run_star_extras.f90 files between MESA versions that you red the changelog to see what has changed, including function call signatures https://docs.mesastar.org/en/release-r22.05.1/changelog.html#id4

**Comment by Anohita1** [comment]
[build.log](https://github.com/MESAHub/mesa/files/9159825/build.log)
I am new to using MESA. I have been trying to replicate the results of this paper 
"A helium-flash-induced mixing event can explain the lithium abundances of red clump stars" for one of my projects. The required MESA input/output files are available on zenodo. 

https://zenodo.org/record/4688026#.YtlUF9JBxNg

I get the following error while trying to compile.

../src/run_star_extras.f90:381:39:

  381 |             screening_mode, s% theta_e(k), &
      |                                       1
Error: 'theta_e' at (1) is not a member of the 'star_info' structure

I am using the latest version r22.05.1
MESA SDK : mesasdk-x86_64-linux-22.6.1

As far as I understand there is some problem with the run_star_extras.f90 file. But I could not fix the error. Is there any way out?

**Comment by fxt44** [comment]
the zenodo entry says:

_using MESA release r15140_ 

so it may be best to use this version. otherwise, as noted above, one will need to convert the 15140 run_star_extras.f90 to r22.05.1.

**Comment by Anohita1** [comment]
Sorry, I did try to use r15140 with the corresponding older MESA SDK version but the build failed.

**Comment by Anohita1** [comment]
Thank you @fxt44. I used r15140 and it did compile. However, on running I am getting the following errors:

**_WARNING: Failed to find eos namelist in file: inlist_io
 WARNING: Failed to find kap namelist in file: inlist_io_**

All this and more are saved in the LOGS directory during the run.
load saved model models/1.00M_at_first_flash.mod

                    WARNING -- inlist initial_z ignored    1.4000000000000000D-02
                          using saved initial_z instead    1.6899999999999998D-02

 failed to recognize item for profile columns: cv
 star_set_profile_columns ierr          -1
 do_star_job_controls_after ierr          -1
 before_evolve_loop ierr          -1


The LOGS file is empty

**Comment by rjfarmer** [comment]
>failed to recognize item for profile columns: cv

You are asking for profile output that MESA does not understand, again the available output columns change with each MESA version. You'll need to delete "cv" from your profile_columns.list file.
