### ISSUE TITLE
orbital velocity in "/binary/private/binary_wind.f90"

### ISSUE THREAD

**Issue by xiaoe475** [MESAHub/mesa#433]
At line 118 of "/binary/private/binary_wind.f90", only `b%m(s_i)` is taken into account. However, in Hurley et al 2002 eq. 8, the orbital velocity is $v_{\rm orb}^2=\frac{GM_{\rm b}}{a}$, where $M_{\rm b}$ is the **total mass of the binary** (eq. 5 in Hurley et al. 2002), and $a$ is the orbital separation. 

Is there a small mistake?

**Comment by warrickball** [comment]
Just had a quick look and this does look like a bug. Here's the offending line:
https://github.com/MESAHub/mesa/blob/c3ccc90c4361e9cac96ade42b324a1b7c285e745/binary/private/binary_wind.f90#L117-L118
I presume the solution is to change line 118 to something like
```f90
v_orb = sqrt(standard_cgrav * (b% m(1) + b% m(2)) / b% separation)
```
