### ISSUE TITLE
rate error in MESA

### ISSUE THREAD

**Issue by 200k33p3r** [MESAHub/mesa#440]
During the MESA summer school 2022, I tried to run minilab1 task3 from Rob's lab using 'approx21_cr63.net' as the network and the code crashed which appears to be an issue with a bad reaction somewhere in MESA. See file attached.

[cr63_out.log](https://github.com/MESAHub/mesa/files/9328773/cr63_out.log)

**Comment by maygpedersen** [comment]
This error occurred at my table during the summer school and I was able to reproduce it on my own laptop
