### ISSUE TITLE
Possible problem with approx21_ cr60.net

### ISSUE THREAD

**Issue by claudiarreyes** [MESAHub/mesa#441]
During MESA School 2022 trying to run Minilab 1 Task 3 with net approx21_ cr60.net, the run ends with an unexpected overshooting boundary error:

```
k, k_a, k_b          73          73          73
 s%top_conv_bdy(i)= T
 D(k)   0.0000000000000000
 s%D_mix(k+1)   5.3213063366042892
 s%overshoot_D_min   100.00000000000000
 Invalid location for overshoot boundary: cz_bdy_dq, dq=   2.0143819758416136E-002   1.0719143572387457E-003
                                 WARNING: rel_run_E_err        1822    5.6127709117969959D-01
terminated evolution: nonzero_ierr
```

Run work directory from Minilab 1 from Rob Farmer's Core Collapse Supernova Lecture (Task 3) with net 'approx21_ cr60.net' until it crashes.

*** This could also be caused by a resolution problem of the model.

**Comment by evbauer** [comment]
Thanks for the report! This is actually an overshoot bug that was recently fixed. See #400. Fix will be in next release.
