### ISSUE TITLE
control Convective_bdy_weight

### ISSUE THREAD

**Issue by annethoul** [MESAHub/mesa#442]
Evan asked me to report this as a bug.

The control  convective_bdy_weight was available in version 12115. It is not available in 12778 and later.

Doc:
       !### convective_bdy_weight
        !### convective_bdy_dq_limit
        !### convective_bdy_min_dt_yrs

        ! Mesh function to enhance resolution near convective boundaries
        ! including regions that are newly nonconvective because of moving boundary.
        ! EXPERIMENTAL

       convective_bdy_weight = 0
       convective_bdy_dq_limit = 1d-4
       convective_bdy_min_dt_yrs = 1d-3

When it was available I produced the following plot, which shows that it worked at least in some cases to smooth the convective boundary. I would like to test this control more extensively to understand what it does and where it works. 
So it would be nice to restore those controls.
![cpm_conv_bdy_weight](https://user-images.githubusercontent.com/56915840/184422354-f25b986f-2020-415f-940d-674f9698bc3f.png)

**Comment by fxt44** [comment]
it is available in r12778 as a run_star_extras

% ls /Users/fxt/mesa_work/r12778/star/test_suite/other_physics_hooks/src
% more /Users/fxt/mesa_work/r12778/star/test_suite/other_physics_hooks/src/convective_bdy/convective_bdy.inc

perhaps a similar run_star_extras can be implemented in more recent releases.

**Comment by fxt44** [comment]
and i remembered this exchange:

```
On May 26, 2020, at 10:28 AM, Bill Paxton <paxton@kitp.ucsb.edu> wrote:

please take a look at star/test_suite/other_physics_hooks where this is an implementation of convective_bdy_weight done in run_star_extras.  use that as a guide.

-b


```


```
On May 26, 2020, at 10:24 AM, Joel Ong via Mesa-users <mesa-users@lists.mesastar.org> wrote:

Greetings all,

The controls namelist entries convective_bdy_weight and associated parameters appear to have been removed in r12778 without any documentation in the release notes. Without these options, I'm obtaining discontinuous evolution of some quantities associated with g-mode oscillation frequencies on the red giant branch, where the boundary of the surface convection zone moves inwards over time (see attached plots). Is there any way to restore these options in r12778?

Best regards,
Joel Ong
```

**Comment by evbauer** [comment]
Yes, but it looks like Bill deleted it from the `other_physics_hooks` test case shortly after the github transition. Anne's example seems to suggest this is an important control, so I would be in favor of promoting it back to an inlist option.

**Comment by annethoul** [comment]
Joel's example also shows that having a discontinuous convective boundary has an important effect on the g-mode frequencies:
![r12778](https://user-images.githubusercontent.com/56915840/184425634-d7f6e77b-3804-47c6-8ca9-faaebef28a22.png)
![r10398](https://user-images.githubusercontent.com/56915840/184425641-0181cb26-4b24-4649-b4e4-451d342b7160.png)

**Comment by darthoctopus** [comment]
For some context: these figures show the evolution of the dimensionless g-mode phase $\epsilon_g = 1/(\nu_g \Delta\Pi_\ell) - n_g$ for the first 10 g-modes (indexed by radial order $n_g$). The figure with the colourbar shows what I obtained for an evolutionary sequence of subgiant models in MESA r10398, and the other shows what I obtained with r12778.

**Comment by evbauer** [comment]
Thanks Joel. This has been on the back burner for a while, but I agree this needs attention. I'll schedule some time to dig into this in a few weeks if nobody gets to it before then. That should be a good time to pick #425 up again as well.

**Comment by evbauer** [comment]
@darthoctopus, if you're interested in testing, it would be great to see whether this restored version of the control might resolve your seismology issues as well.
