### ISSUE TITLE
FPE in do_scan_grid during fast_scan_grid

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#447]
https://testhub.mesastar.org/rf%2Ffpe/commits/0fbd67e/test_cases/astero/fast_scan_grid

In do_param we start at k=max_parameters and work down the list. But param(max_parameters) is not set. The set_starting_values call only initializes the param's that are set, not the unset ones.

**Comment by warrickball** [comment]
Though this particular astero FPE is fixed, there are a bunch more (all benign as far as I can tell) lurking in the output of the frequency "ratios". I know about them but the routines for computing those ratios are fundamentally flawed anyway, so I'm not inclined to fix them until I have a chance to overhaul the whole thing.
