### ISSUE TITLE
We need a better core collapse defintion

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#451]
Currently we mostly relay on the fe_core_infall parameter to denote when we are at core collapse. Unfortunately I keep seeing cases
where we get a velocity spike that triggers the exit condition, while we are still along way from collapse.

We currently compute fe_core_infall here https://github.com/MESAHub/mesa/blob/bea719ff019a2b9aace94988f54d005f56f15f63/star/private/report.f90#L397 

I expect we want something instead like making sure X amount of mass is collapsing at fe_core_infall velocity, rather than a single zone.

**Comment by fxt44** [comment]
yes. X amount of iron core mass, or N zones within the iron core have reached fe_core_infall.
