### ISSUE TITLE
MESA Rotation

### ISSUE THREAD

**Issue by Chrrrrris** [MESAHub/mesa#454]
Hi, I am new to MESA, so please bear with me if this question looks too stupid. 
I've been using MESA to simulate the evolution Pre-Main Sequence stars. In my project, I need to set up an initial rotation rate for the pre-main sequence star to evolve, so that when the star reaches the ZAMS, it has exactly a particular rotation velocity (say 1 rev per day). I can certainly try different initial rotation rates and see how the rate changes when the star evolves to the ZAMS, but since I will be simulating many different stellar models with different stellar mass and metallicity, that is probably not feasible since the initial condition would then be different for each different model. I'm wondering whether there is a more efficient solution to set up an initial rotation rate so that the rotation rate at ZAMS evolve exactly to a particular value? Any help would be really appreciated!!!
Chris

**Comment by rjfarmer** [comment]
There are options to have rotation only turn on near zams https://docs.mesastar.org/en/release-r22.05.1/reference/star_job.html#set-near-zams-omega-div-omega-crit-steps  but that does imply the pre-MS is evolved without rotation.

**Comment by Chrrrrris** [comment]
> There are options to have rotation only turn on near zams https://docs.mesastar.org/en/release-r22.05.1/reference/star_job.html#set-near-zams-omega-div-omega-crit-steps but that does imply the pre-MS is evolved without rotation.

Hi Robert, thanks for your reply! Yes I know there is an option to set up rotation when the star is near ZAMS, but I want to know how the PMS evolves with rotation though. Any advice on setting the initial rotation rate for the PMS model so that the PMS evolves to a particular rotation rate when it reaches ZAMS?

Also I realized Github may not be the best place to ask this question; I would throw this question in the MESA mailing list!
