### ISSUE TITLE
Wrong X_0 in OSC and FGONG files when initial_y < 0

### ISSUE THREAD

**Issue by AntoNoll** [MESAHub/mesa#465]
Hi everyone,

I noticed that, both in FGONG and OSC files, when `initial_y` < 0, the initial hydrogen abundance is wrong. This is due to the fact that it is defined as `global_data(5) = 1d0 - (s%initial_y + s%initial_z)` in both `star/private/pulse_fgong.f90` and `star/private/pulse_osc.f90`. An easy fix should be to implement the enrichment law in both files (in which case I can do a PR). But, maybe there is a safer way to directly obtain the _actual_ initial helium abundance?

**Comment by warrickball** [comment]
Confirmed in the latest commit (c295eeb). You're right that it'd be safer to consistently set the actual initial Y. At a glance, the same enrichment law Y=0.24+2Z is implemented in at least three places, which might warrant refactoring anyway.
```
$ grep initial_y star/private/*.f90 | grep 24
star/private/create_initial_model.f90:         if (initial_y < 0) initial_y = max(0d0, min(1d0, 0.24d0 + 2d0*initial_z))
star/private/pgstar_production.f90:            if (initial_y < 0) initial_y = max(0d0, min(1d0, 0.24d0 + 2*initial_z))
star/private/pre_ms_model.f90:         if (initial_y < 0) initial_y = max(0d0, min(1d0, 0.24d0 + 2*initial_z))
```
I don't think we have any initial step that checks or resets controls before the evolution begins. Somewhere near the start of `model_builder` in `star/private/init.f90` might be a place to set `s% initial_y` to the value from the enrichment law. We might then have to catch that PGstar call.

**Comment by warrickball** [comment]
I've just created a new branch `fix_pulse_X0` (3b2ab53a) to try fixing this by resetting `s% initial_y` in `star/private/init.f90`.

**Comment by AntoNoll** [comment]
Thanks! It should indeed allow a more reliable access to the initial helium abundance.
