### ISSUE TITLE
Actions on forked repos fail because of email & password

### ISSUE THREAD

**Issue by matthiasfabry** [MESAHub/mesa#473]
When committing to branches on my fork, the github actions automatically start with a compilation check.
This is all good, until the action `Build MESA` always fails because of a email & password issue?

https://github.com/matthiasfabry/mesa/actions/runs/3748150154/jobs/6365158998#step:9:1436

I get notified by email, which happens a lot. I could turn this off, but I _want_ to be notified when compilation failed because of an actual hiccup in the syntax.

Note that the `Build on linux with SDK` always succeeds when the email & password thing props up with `build MESA`

**Comment by warrickball** [comment]
The failures are coming from the action "Build MESA" that we've disabled in the main repo. That was an attempt to automatically send the compilation results to our TestHub but I don't think it ever worked. There's a second action "Build on Linux with SDK" that still compiles MESA but doesn't submit the results to TestHub.

It looks to me like you want to disable the "Build MESA" action in your fork. I'm not sure why the fork didn't copy the fact that we've disabled that action.
