### ISSUE TITLE
Small typo in sample code on Using MESA page

### ISSUE THREAD

**Issue by drpiccioni** [MESAHub/mesa#478]
Here is a code snippet from the section called "A Temperature-Density Profile" on [https://docs.mesastar.org/en/release-r22.11.1/using_mesa/output.html]:
```python
%pylab
import mesa_reader as Mr

# load entire LOG directory information
l = MesaLogDir('./LOGS')
# grab the last profile
p = l.profile_data()

# this works even if you only have logRho and logT!
loglog(p.Rho, p.T)
xlabel("Density")
ylabel("Temperature")
``` 

The fifth line should be:
```python
l = mr.MesaLogDir('./LOGS')
```

no?

And does the tenth line also need attention?

**Comment by wmwolf** [comment]
Yes, I think we need to prefix the call to the `MesaLogDir` constructor with `mr`. Good catch!

> And does the tenth line also need attention?

Can you elaborate on what you mean regarding line 10?

**Comment by drpiccioni** [comment]
Maybe it’s just me. What does loglog do?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wmwolf** [comment]
Matplotlib's `loglog` creates a log-log plot (note how both axes are logarithmic in the example), so I think that line's okay.

**Comment by wmwolf** [comment]
Fixed directly on `main` in commit `152c8fd`.

**Comment by drpiccioni** [comment]
Of course. 
Thanks!

**Comment by evbauer** [comment]
FYI, I pushed this documentation change onto the `release/r22.11.1` branch as well so that it shows up in the default version of the documentation.
