### ISSUE TITLE
Turn off gold_tolerances2 in defaults?

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#490]
So we keep having a discussion about this and I want to try and see if we can make a decision on this.

We/I have had many reports from users about MESA getting harder to evolve in versions post ~15140. I think some of this can be attributed to the tighter tolerances implied by use_gold_tolerances2=.true. in the defaults. While we want tighter controls in test cases to make sure MESA gets better, its not clear that forcing users to have this on in the defaults is beneficial, especially with people doing stellar engineering to models.

I propose we turn off gold_tolerances2 in the controls defaults and instead just add it to the test suite cases. That way it's clearer to users that this is an option they may want to enable/disable.

**Comment by fxt44** [comment]
i have no objection to this suggestion. is there evidence that turning off use_gold_tolerances2 actually alleviates "harder to evolve"?

**Comment by rjfarmer** [comment]
I generally turn it off when starting a project as it seems to make things easier, but I don't have a formal test of this.

**Comment by fxt44** [comment]
would a (full) test suite run with use_gold_tolerances2=.false. be useful to try?

**Comment by rjfarmer** [comment]
https://testhub.mesastar.org/main/commits/c13e2a4

**Comment by evbauer** [comment]
I would be in favor of this.

I've had intermittent encounters with gold2 tolerances making models harder to evolve. Turning them off usually doesn't solve my problem, but it has helped often enough that it is part of my workflow of things to check now, especially for binary evolution involving degenerate objects.

**Comment by evbauer** [comment]
I also think the gold2 tolerances are largely related to the push for better energy conservation circa MESA V, but in light of the nuances pointed out in MESA VI section 5, I'm not sure it's sensible to push for that level of conservation by default.

Related to this, I would suggest significantly relaxing the default values for `max_abs_rel_run_E_err` and `warn_when_large_rel_run_E_err`.

**Comment by fxt44** [comment]
full test suites rolling on c13e2a4. this will be interesting on several levels!

**Comment by fxt44** [comment]
_Related to this, I would suggest significantly relaxing the default values for max_abs_rel_run_E_err and warn_when_large_rel_run_E_err._

yes. i do this habitually.

**Comment by evbauer** [comment]
https://github.com/MESAHub/mesa/blob/c13e2a49c69be60ed39858fdaa30f35c5637f1b9/star/defaults/controls.defaults#L11430

I would change this default value to `0.1d0`.

https://github.com/MESAHub/mesa/blob/c13e2a49c69be60ed39858fdaa30f35c5637f1b9/star/defaults/controls.defaults#L1787

I would change this default value to `1d0`, or perhaps even `1d99` to be effectively off by default.

**Comment by rjfarmer** [comment]
Looks like nothing changed other than cburn_inward. On the other hand alot of test cases are already tweaking use_gold2_tolerances, the gold2 tolerances themselves, or setting steps_before_use_gold2_tolerances. So maybe alot of test cases didn't even notice the change in the tolerances?

**Comment by fxt44** [comment]
cburn_inward fails only on one machine. two machines running the full test suite passed cburn_inward.

wow. didn't expect this result from turning off gold2.

on one machine (vega): total time was 73211 seconds. on a previous run on main: total time was 80717 seconds. so ~10% more efficient from gold2 off.

as turning off gold2 doesn't seem to have much impact on the test suite, it alone seems unlikely to account for the perception of "getting harder to evolve" post 15140.

**Comment by rjfarmer** [comment]
Turns out alot of stuff is playing with the flag anyway so changing the defaults didn't actually do anything.

- 20M_pre_ms_to_core_collapse explicitly sets it on https://github.com/MESAHub/mesa/blob/7680ab3ea55b36a06c58bcaedafa8795e6d05ec5/star/test_suite/20M_pre_ms_to_core_collapse/inlist_common#L172
- ppisn explicitly turns it off https://github.com/MESAHub/mesa/blob/a130cfd35092752c08a67e8924866863381f5efe/star/test_suite/ppisn/inlist_ppisn#L88 

I'll try another test suite run but force it off in the inlists as well.

**Comment by rjfarmer** [comment]
https://testhub.mesastar.org/rf%2Fno_gold2/commits/073e3dd

**Comment by fxt44** [comment]
test suite rolling on one machine. the other machine is almost finished with c13e2a4.

**Comment by fxt44** [comment]
another timing data point on c13e2a4:
with gold2 on: total time was 90442 seconds.
with gold2 off: total time was 85034 seconds.

**Comment by evbauer** [comment]
I'm also interested in seeing what happens to the test cases that explicitly turn off gold2 if we force them to turn it on. Presumably they would fail or at least have more retries and such?

**Comment by fxt44** [comment]
yep, an interesting experiment to rerun in the modern epoch.

**Comment by warrickball** [comment]
I know I'm late to the conversation but I want to repeat here some stuff I shared a few months ago on Slack (originally 2022-07-19, followed-up 2022-09-06) that I think is relevant. I also found MESA slower post r15140, particularly when I ran a 1.3 Msun model to the base of the RGB. The run hits 10 Newton iterations because it can't get the residuals below about 10⁻⁷. I subsequently discovered that the only relevant changes were indeed some `gold2` tolerances:
```
    gold2_tol_residual_norm2 = 1d-10 ! was 1d-8
    gold2_tol_max_residual2 = 1d-8   ! was 1d-5
    gold2_iter_for_resid_tol3 = 12   ! was 999
    gold2_tol_residual_norm3 = 1d-8  ! was 0
    gold2_tol_max_residual3 = 1d-5   ! was 0
```
My main take home was the question: why we can't solve the equations to better than 10⁻⁷ in a low-mass star on the main sequence? I definitely don't have the bandwidth to see what's happening there any time soon. (I admit I don't remember now what my timestep limits were.) But I'd much rather spend some time on "why can't we meet `gold2` tolerances in mundane cases?"  rather than "can we get away with switching off `gold2` tolerances?".

@evbauer, have you had a look at where your runs appear to be struggling with `gold2` tolerances? Is there a reasonable explanation for why we can't solve the equations better? How easy/hard is it to even find out? Can we make it easier?

My own low-mass models usually struggled with the `dlnE_dt` residual in the outer few hundred zones.

**Comment by rjfarmer** [comment]
>But I'd much rather spend some time on "why can't we meet gold2 tolerances in mundane cases?" rather than "can we get away with switching off gold2 tolerances?".

Worthy goal and I say go for that when you have time. But we have issues all over the parameter space, and it's going to take a long time to whack all the bugs for all types of stars. 

gold2 on for all test cases https://testhub.mesastar.org/main/commits/9b6d902

**Comment by warrickball** [comment]
> Worthy goal and I say go for that when you have time. But we have issues all over the parameter space, and it's going to take a long time to whack all the bugs for all types of stars.

Agreed, though I was surprised (verging on alarmed) that we have struggle to get the residuals down even for a low-mass main-sequence star. 

If we accept it's an issue, then I don't see the point imposing a default that will never succeed anyway, so am in favour of dropping `gold2` as default.

**Comment by fxt44** [comment]
ok, three gold2 experiments have been run. what do we conclude? next step(s)?

**Comment by rjfarmer** [comment]
I think we can conclude that in general test cases don't care that much whether gold2 is on or not. Some break, some get better, some worse, whether gold2 is on or not.

So at first, it looks like it doesn't matter, but we have to ask how representative the test suite is, as it has been tuned to run well during testing.

**Comment by fxt44** [comment]
second. so we can consider gold2 off as the default. 

want to  try evan's suggested experiment of setting max_abs_rel_run_E_err = 1d99 and warn_when_large_rel_run_E_err = 0.01 on the whole test suite?

**Comment by rjfarmer** [comment]
relaxing the E_err controls https://testhub.mesastar.org/main/commits/4c04099

**Comment by rjfarmer** [comment]
This one finally ran and finished

https://testhub.mesastar.org/main/commits/84b4f14

**Comment by fxt44** [comment]
interesting! got two full test suite runs rolling on this now.

**Comment by fxt44** [comment]
wow! did not expect that from setting max_abs_rel_run_E_err = 1d99 and warn_when_large_rel_run_E_err = 0.01 .

so far it seems we could turn off gold2 and relax the rel_run_E_err defaults. unless i'm missing something, i think we're not seeing large cpu differences with any of these turned off/on.
