### ISSUE TITLE
No RTI mixing in CCSN?

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#503]
It seems in 181c9fac0 we got a check for rho < 1d99 in the RTi code (https://github.com/MESAHub/mesa/blob/dd2570f4c99ad3e9874faac25986b0ba6fc3edcb/star/private/hydro_alpha_rti_eqns.f90#L140)

That has the effect of turning off the source_plus term in RTI (source_minus is still set). This has the effect that in plots of mixing during a CCSN we see no RTi mixing. Removing the if statement (See #502) puts RTI mixing back on the mixing plot. 

Is this the right fix? In the past it seems there was an s% rho(k) < s% alpha_RTI_src_min_rho check, but s% alpha_RTI_src_min_rho has been removed. So do we need this control back? 

Also, given the code got heavily rewritten after this point (for TDC and converting to auto_diff)  how confident are we that the rest of the code is working? as no test case seems to have picked up thats it's been broken?

Also, we need to think about how we can make a test case to detect whether RTI is working or not.

**Comment by fxt44** [comment]
i'm curious why the (integral) ccsn_IIp test suite case did not catch this bug.  i'll look into that. unit tests, like one for rti, are lacking in the current test suite (and always have).

**Comment by rjfarmer** [comment]
I expect it didnt catch it as unless your looking at the pgplots nothing else will notice if rti is on or not.

**Comment by evbauer** [comment]
Ouch! Thanks for finding this.

RTI is a capability advertised at length in a MESA instrument paper (MESA IV), so I think we had probably better get it turned back on, and ideally have something in the test suite that would notice this kind of breakage.

Perhaps @aurimontem might want to chime in? Jared might be able to point us in the right direction for the best way to make sure this gets tested.

**Comment by fxt44** [comment]
dug in a bit, remembering this one from doing the current documentation. this test case is among the most poorly instrumented. all its looking for to pass is for a shock to reach a certain mass location. there is no sanity checking of the solution at each of its 8 parts. if there had been, this rti failure probably would have been caught.

**Comment by aurimontem** [comment]
Hi! I just got back from travel and can confirm the bug. Has this been fixed? I've been chatting about this with Rob and I'm happy to plug in too.

As for ways to check whether or not RTI is working, I think would be good to check if the density and composition have been mixed (basically, do the profiles look anything like figures 27-29 in MESA IV). Density might be hard to quantify, but for composition, a simple test could be to identify the outermost mass coordinate where X < 0.1 or 0.01 or some other very small number in the pre-shock model, and then check that X > 0.2 (or some other small but modest value) at that location by shock breakout. You could do a similar test for outward mixing of other species. If the before-and-after checks need to be in one inlist, I think the best would be in inlist_shock_part4 which includes the shock traversing most of the envelope

**Comment by rjfarmer** [comment]
It's not fixed yet. I opened a PR #502 with the fix I think we need. But it would be helpful for someone to confirm this the right fix and whether we need any other changes.

**Comment by aurimontem** [comment]
This looks like the right fix. I'm currently running some comparisons to r15140 where RTI wasn't forced off. Is it worthwhile to also add a physics check to make sure RTI mixing occurred and throw an error if it didn't?

**Comment by rjfarmer** [comment]
Yes having a physics check would be helpful

**Comment by fxt44** [comment]
the c13_pocket test case is well instrumented throughout its evolution. maybe it can help as an example.
