### ISSUE TITLE
possible issue with dx_limit_min_x in release candidate 23.05.1

### ISSUE THREAD

**Issue by mjoyceGR** [MESAHub/mesa#537]
Per controls.defaults:

      ! Limit on magnitude of decrease in any cell hydrogen abundance during a single timestep.
      ! dH here is ``abs(xa(j,k) - xa_old(j,k))`` for any cell k and all species j, eg 'h1', 'he4', etc.
      ! special 'species' X (any hydrogen), Y (any helium) and Z (any metals) are
      ! allowed here. E.g. 'Z' will trigger the timestep control if any metal isotope
      ! abundance individually satisfies the conditions below.
      ! Considers all cells except where have convective mixing.

    dX_limit_species(1) = 'h1'
    dX_limit_species(2) = 'he4'
    dX_limit_species(3:) = ''

      ! dX_limit_min_X
      ! ~~~~~~~~~~~~~~

      ! dX limits only apply where xa(j,k) >= this limit.

      ! ::

    dX_limit_min_X(:) = 1d99

However, when I specify

`dX_limit_species(1) = 'h1' `
` dX_limit_min_X(1) = 1d-2`

in `&controls`, I receive

> At line 666 of file ../private/ctrls_io.f90
> Fortran runtime error: Bad data for namelist object dx_limit_min_x

The error is the same when I use `dx_limit_min_X(:)` and similar variations (e.g. specifying the rest of the `dX_limit_species` array)

This is an attempt to replicate use of 
 `dH_limit_min_H = 1d-2` 
 which works with version 15140

**Comment by mjoyceGR** [comment]
these parameters are from an `inlist` that works with 15140; I had not commented them out because I was updating parameter names line-by-line, but commenting them out seems to have fixed the issue. However, when uncommented, the error message (incorrectly) identifies `dX_limit_min_X` as the source of the problem.
Is there an internal conflict between `dX_limit_min_X` and any of the following?

`& controls !! for 15140`
`!      dH_limit_min_H = 1d-2`
`!      dH_limit = 0.1`

`!      dH_div_H_limit_min_H = 1d-5`
`!      dH_div_H_limit = 0.5`

**Comment by evbauer** [comment]
I can't easily reproduce this, but all I tried so far was just adding `dX_limit_min_X(1) = 1d-2` to a fresh work directory. It could be that some more elusive namelist nonsense is going on. Could you attach your specific inlist so I could try it out?

**Comment by evbauer** [comment]
Oh wait. I guess I was going too fast and hadn't digested the meaning of the second comment. I did manage to reproduce this by adding in the block of controls from the old MESA version, uncommented:
```
      dH_limit_min_H = 1d-2
      dH_limit = 0.1

      dH_div_H_limit_min_H = 1d-5
      dH_div_H_limit = 0.5
```
Interestingly, I can get the error message to point to the wrong thing depending on where I put the bad control in the inlist. E.g. it gives

> Fortran runtime error: Bad data for namelist object dx_limit_min_x

if the bad control comes right after `dX_limit_min_X(1) = 1d-2` in the inlist. But if I move it to be right after `xa_central_lower_limit(1) = 1d-3`, then it gives

>  Bad data for namelist object xa_central_lower_limit

It seems to only point to the wrong thing when it comes after an inlist control that is an array. Maybe I can decipher why that is...

**Comment by warrickball** [comment]
So, if I've understood correctly, the issue is that the error message points to the wrong namelist element if you leave the old (deprecated) controls in the inlist? This looks like a basic Fortran limitation, not a MESA issue. I just tried this small program `bna.f90`:
```f90
program bna

  implicit none

  integer, parameter :: dp = KIND(0.0d0)
  integer :: iounit, ierr
  real(dp) :: scalar, vector(3)

  namelist /test/ scalar, vector

  open(newunit=iounit, file='test.nml', status='old', iostat=ierr)
  read(iounit, nml=test)
  close(iounit)

  write(*,*) scalar
  write(*,*) vector

end program bna
```
with this namelist in `test.nml`:
```
&test
  scalar = 2.5
  vector(1) = 0.2
  bad_namelist = 0.3
/
```
and it fails with the same issue:
```
$ gfortran bna.f90 -o bna.x
$ ./bna.x
At line 12 of file bna.f90
Fortran runtime error: Bad data for namelist object vector
...
```
Note that we've hit the same issue: `bad_namelist` is the non-existent variable but the error says `vector` is the problem.

This isn't the first time we've found Fortran's namelist error reporting unhelpful but it doesn't look like a MESA issue. I'm not sure if we can find or devise a workaround or open a bug report in `gfortran`. (I'll have a look at what `ifort` does later, out of curiosity.)

**Comment by mjoyceGR** [comment]
thanks guys. Agreed that if it's actually compiler issue, it shouldn't be labeled as release blocker

**Comment by warrickball** [comment]
Reported on GCC's bug tracker:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109897

**Comment by warrickball** [comment]
[The first reply](https://github.com/MESAHub/mesa/blob/1d56d4000b5e4b37abd17370a914f3f72d6d3662/star/make/makefile_base#L305-L311) points out that the correct behaviour can be restored by passing `-std=f2018` to the compile command and I've found `-std=f2008` works too. I've made `star` compile the verbose way (`QUIET =` in `star/make/makefile`) and can see that `ctrls_io.f90` isn't normally compiled with the `-std=f2008` flag, though most other stuff is. I've tried removing `ctrls_io.f90` from this clause that distinguishes it:

https://github.com/MESAHub/mesa/blob/1d56d4000b5e4b37abd17370a914f3f72d6d3662/star/make/makefile_base#L305-L311

and `star` seems to compile anyway. Do either of you want to try that change to see if the namelist error correctly identifies the bad item?

While we're at it, it isn't obvious why any of those source files are compiled without the `-std=f2008` flag so I'll have a go at reducing the exceptions there.

**Comment by warrickball** [comment]
It looks like it's enough to add the `-std=f2008` flag to the `WORK_COMPILE` definition that the `work` directories use:
```
$ git diff main
diff --git a/utils/makefile_header b/utils/makefile_header
index 4e38737c..f17a5ed2 100644
--- a/utils/makefile_header
+++ b/utils/makefile_header
@@ -234,7 +234,7 @@ COMPILE_DEVEL     = $(COMPILE_NO_OPT)
 
 WORK_COMPILE = \
    $(FC) $(FCbasic) $(FCopenmp) $(FCchecks) $(FCdebug) $(FCfree) \
-   -I$(MESA_INCLUDE_DIR) -I$(WORK_SRC_DIR) -c
+   $(FCstandard) -I$(MESA_INCLUDE_DIR) -I$(WORK_SRC_DIR) -c
 
 ifeq ($(USE_PGPLOT),YES)
        WORK_COMPILE += -DUSE_PGPLOT
```
@evbauer or @mjoyceGR, could you try this too? You shouldn't need to rebuild MESA or `star`, just `./clean` and `./mk` the `work` folder where you're encountering the issue. I'll also test this on a branch to see if the test suite breaks and if `binary` or `astero` need similar changes.

Changing the flags for `star_def`, `star_lib`, `ctrls_io` and `star_job_ctrls_io` neither helps nor harms. I'm inclined to remove their special treatment to keep things simple but that's a separate issue.

**Comment by mjoyceGR** [comment]
seems like you're beyond this point now, but I also confirm that the namelist reporting issue is resolved with Warrick's flag
