### ISSUE TITLE
atmosphere user guide is down

### ISSUE THREAD

**Issue by Steinerkadabra** [MESAHub/mesa#540]
Hi MESA team, 

I have no clue wether this is the correct way to make you aware of this so I want to apologise if not. 

**Describe the bug**
The link to the atmosphere user guide in the MESA documentation leads to the old mesa.sourceforge page and is not reachable. 

**To Reproduce**
1. Go to the [changelog](https://docs.mesastar.org/en/release-r22.11.1/changelog.html#changes-in-r12778) in the docs or the [mailing list entry](https://lists.mesastar.org/pipermail/mesa-users/2019-September/010470.html)
2. Click on the link to http://mesa.sourceforge.net/assets/atm-user-guide.txt
3. See error

Best,
Thomas

**Comment by Steinerkadabra** [comment]
Perfect! Thank you Evan!

**Comment by warrickball** [comment]
At a glance, it looks like the information in that file is basically the same as what's in the [module docs for `atm`](https://docs.mesastar.org/en/release-r22.11.1/modules.html#atmospheres-atm), so the solution might be for the changelog to point there and/or MESA VI.

**Comment by evbauer** [comment]
I've gone ahead and fixed the link to the version of the changelog on the docs website:
https://docs.mesastar.org/en/latest/changelog.html#changes-to-atmospheres

So at least the text file is available somewhere now. I'm afraid there isn't much we can do about the broken link from the old mailing list post.
