### ISSUE TITLE
Bad logT guess value for entropy relaxation in eosDE mode

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa#548]
Spurred by this mesa-users post: https://lists.mesastar.org/pipermail/mesa-users/2023-June/014529.html

It looks like the issue here is that the EOS needs to solve for temperature given density and energy, but is unable to converge to the right answer in a reasonable number of iterations because the initial logT guess is bad.

That's set here:
https://github.com/MESAHub/mesa/blob/295a043c38de7f25720cd2d39221d47bda3375da/star/job/run_star_support.f90#L3060-L3062

For very low input energy (~10^10 erg/g), this selects `T_guess_rad` (~10^6 K) when it should select `T_guess_gas` (~10^2 K) as our initial guess. I believe the `max` in that last line should be a `min` to select the most reasonable temperature guess.

**Comment by fxt44** [comment]
nice catch!

might there be cases where the larger temperature (either one) is a more appropriate guess?

**Comment by evbauer** [comment]
I don't think so. My understanding of the logic here is that we want to select whichever of radiation and ideal gas would have a dominant contribution to the energy in a given temperature ballpark, and I think this leads to an understandable sign error in the implementation.

If at fixed internal energy, radiation energy gives a _larger_ `T_guess` value than ideal gas does, then we're actually saying that radiation needs a higher temperature to achieve the relevant energy scale -> ideal gas is dominant -> we should select ideal gas instead of radiation. So I think we always want `min` instead of `max` here.

I guess I should check with @orlox if that all tracks with the right intent, since I assume he was the one that implemented these relaxation features?

**Comment by fxt44** [comment]
this makes sense. thanks. i double check from pablo would be useful.
