### ISSUE TITLE
atm name mismatch

### ISSUE THREAD

**Issue by Debraheem** [MESAHub/mesa#567]
See https://lists.mesastar.org/pipermail/mesa-users/2023-July/014640.html.

I think Anwesha has found a documentation bug? looking in $MESA_DIR/atm/atm_data/ there is:

"db_wd_tau25.tbl", and "wd_25.tbl"

where as the current documentation on MESA docs states:

'WD_tau_25' | Use model atmospheres for cool white dwarfs, via Rohrmann et al. (2011, MNRAS, 411, 781) treatment. Surface optical depth is 𝜏surf=25.12τsurf=25.12.
-- | --
'DB_tau_25' | Use model atmospheres for hot(ter) white dwarrfs, provided by Odette Toloza based on Detlev Koester’s atmosphere code. Surface optical depth is 𝜏surf=25.12τsurf=25.12.

-------

It appears that setting atm_table_option = 'WD_tau_25' works, but 'DB_tau_25' does not. 
I think the correct documentation should state 'DB_WD_tau_25' instead of 'DB_tau_25'?

**Comment by evbauer** [comment]
Agreed! Fixed in 72b68a1 and da0bb47 (one is for `main` and the other is the release branch that the documentation currently points to by default.)
