### ISSUE TITLE
SDK resources moved or missing?

### ISSUE THREAD

**Issue by rieder** [MESAHub/mesa#586]
Hi,

The link to the SDK on https://docs.mesastar.org/en/release-r23.05.1/installation.html to the installation instructions of the SDK (http://www.astro.wisc.edu/~townsend/static.php?ref=mesasdk) is dead.
The download locations for fpx3 and lapack95 that were previously at http://www.astro.wisc.edu/~townsend/resource/download/sdk2/src/ are now also not working (we use these in the AMUSE interface for MESA 15140). Have these been moved? 
If so, what is the new link?

Thanks, Steven

**Comment by rieder** [comment]
(see also https://github.com/amusecode/amuse/issues/980)

**Comment by evbauer** [comment]
The link on the MESA docs website was somewhat recently updated to http://user.astro.wisc.edu/~townsend/static.php?ref=mesasdk

Does that solve your issue?

**Comment by rieder** [comment]
Not completely. We use a download script (https://github.com/amusecode/amuse/blob/main/src/amuse/community/mesa_r15140/download.py) to get the packages in the SDK and build them ourselves - but the source files have moved and I can't find the new link on that page.

**Comment by evbauer** [comment]
Ah, thanks! @rhdtownsend can you help us out with that?

**Comment by rieder** [comment]
> The link on the MESA docs website was somewhat recently updated to http://user.astro.wisc.edu/~townsend/static.php?ref=mesasdk

there's at least one non-working link on the docs website (under "Confirm that you installed the MESA SDK correctly

Please check that you followed the MESA SDK [installation instructions](http://www.astro.wisc.edu/~townsend/static.php?ref=mesasdk). Pay particular attention to the prerequisites for your system.")

**Comment by rhdtownsend** [comment]
The revised link for the SDK2 sources:

http://user.astro.wisc.edu/~townsend/resource/download/sdk2/src/

**Comment by evbauer** [comment]
Thanks! Just fixed the two broken links that were near [here](https://docs.mesastar.org/en/release-r23.05.1/installation.html#confirm-that-you-installed-the-mesa-sdk-correctly) on that page.

**Comment by rieder** [comment]
Thanks!
