### ISSUE TITLE
documentation possibly out-of-sync 

### ISSUE THREAD

**Issue by mathren** [MESAHub/mesa#595]
In `$MESA_DIR/star/defaults/controls.default` there is the following description for `max_mdot_jump_for_rotation`. The note suggests to couple this with `vcrit_max_years_for_timestep`, which however does not appear elsewhere in the docs, nor in $MESA_DIR/star/private/*.f90`. 

This is a control useful for any stellar model approaching critical rotation, and it seems to have an effect regardless of `vcrit_max_years_for_timestep`. I suspect this is just a case of documentation getting out of sync with the code, but I would not be sure how to fix it.

```
      ! max_mdot_jump_for_rotation
      ! ~~~~~~~~~~~~~~~~~~~~~~~~~~

      ! Don't increase prev mdot by more that this.
      ! NOTE: use ``vcrit_max_years_for_timestep`` with this.

      ! ::

    max_mdot_jump_for_rotation = 2
```

**Comment by evbauer** [comment]
You are quite right! In fact, it turns out that `vcrit_max_years_for_timestep` was deleted fully 10 years ago in November 2013, svn revision 5582. I'll delete that note. Thanks!
