### ISSUE TITLE
MESA Jenkins CI Builds are Failing

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa#601]
The Flatiron Jenkins builds on `main` seem to be failing over the last couple of weeks. E.g. see
https://jenkins.flatironinstitute.org/blue/organizations/jenkins/mesa/detail/main/342/pipeline/7

Should we disable? @matteocantiello @dylex

**Comment by fxt44** [comment]
it is now

http://user.astro.wisc.edu/~townsend/resource/download/mesasdk/mesasdk-x86_64-linux-21.4.2.tar.gz

**Comment by matteocantiello** [comment]
Thanks Dylan and Frank for looking into this so quickly

M

--
Matteo Cantiello - https://www.stellarphysics.org/
Research Scientist,  CCA, Flatiron Institute
Visiting Associate Researcher, Princeton University

Sent via Superhuman iOS ***@***.***>

**Comment by dylex** [comment]
This should be working again.  Build is running on main now.

**Comment by evbauer** [comment]
Thanks so much Dylan! Submitting the test results to testhub seems to be working great again.

It looks like Jenkins is running over the test suite on the head of main a second time, this time with the message "Branch indexing". Is that normal? https://jenkins.flatironinstitute.org/blue/organizations/jenkins/mesa/activity?branch=main

**Comment by dylex** [comment]
If you're talking about builds 344 and 345, 345 is the normal run. 344 I had submitted manually so was the exception.

**Comment by evbauer** [comment]
Ah, I see. That's perfect. Thanks for getting this resolved so fast!
