### ISSUE TITLE
Hole in EOS at boundary between HELM and ideal at low temperature, high density

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa#614]
See the attached plot for gas pressure for pure carbon. HELM has a pressure floor  of `1e-20`, and MESA seems to be picking this up right at the edge of where we switch from HELM to ideal. I think what should be happening here is that HELM should just error out and we fall back to ideal. Perhaps we could just remove the pressure floor since now we have the ideal backstop behind HELM. I'm investigating further, but would also be interested to hear from @fxt44 if you have any thoughts.

Reported by Didier Saumon (LANL).

![iTerm2 mwtfu8 eos_plotter](https://github.com/MESAHub/mesa/assets/18405113/9ba079d2-1938-4741-bc81-9bd71bec101d)

**Comment by fxt44** [comment]
i don't know why there is a pressure floor. it might be an attempt to get around helm assuming full ionization. i agree with removing the pressure floor and falling back to an ideal gas of atoms.

**Comment by evbauer** [comment]
Hmmm, poking around the commit history reveals some extended discussion about FPE's associated with overlflow/underflow that motivated moving the floor from `1d-99` to `1d-20`. See #271 and #101. So I'm a bit hesitant to just do away with it, but I'll look closer at how to get this to fall back to ideal under normal circumstances.

**Comment by evbauer** [comment]
So here's my first attempt at this: 06618e760868017046c5b98dc25319db79d34afe

It turns out that the `egas` and `sgas` floors were kicking in even earlier than where the `Pgas` hole was showing up, so this causes bailing to neutral ideal gas for a larger region. Attached is what the EOS regions plot looks like with this change. (Compare to our docs page: https://docs.mesastar.org/en/release-r23.05.1/eos/overview.html)

Obviously we'll need to see what testing thinks about this, but it seems like this might be a sensible direction to go?

![iTerm2 dXtXpN eos_regions](https://github.com/MESAHub/mesa/assets/18405113/2500b4a6-a964-4026-bda6-4a845111fb70)
