### ISSUE TITLE
Running log of documentation errors/typos/out-of-date parameter names found at MESA Summer School 2024

### ISSUE THREAD

**Issue by mjoyceGR** [MESAHub/mesa#658]
docs version 24.03.1
in tutorial for modifying `run_star_extras`:

Typos in the directions for adding history column:
`vals(2) = safe_log10_cr(s% R(i) / rsol) ! in solar radii`
should be
`vals(2) = safe_log10_cr(s% R(i) / rsol) ! in solar radii`

When adding an extra profile column
` vals(k,1) = s% Pgas(k)/s% P(k)`
Should be
` vals(k,1) = s% Pgas(k)/s% Peos(k)`

wrong path for the star_ptr information, it should be 
`$MESA_DIR/star_data/public/star_data_*.inc`  
as mentioned in the star info section earlier

with thanks to @BucheleL, @courtcraw

**Comment by maja-jablonska** [comment]
`safe_log10_cr` also didn't work for me - either `safe_log10` or `log10` did.

**Comment by mjoyceGR** [comment]
brilliant, thank you! 10 MESA Summer School points*

*no cash value

**Comment by BucheleL** [comment]
At the end of the paragraph after "Add Stopping Condition", the "when to stop" section in controls.defaults is at line 940 not 230.

**Comment by BucheleL** [comment]
For Zbase in kap controls, it isn't clear what happens with the default value of -1 (does MESA then default to using initial_z?)

**Comment by gautam-404** [comment]
The docs do not explicitly define the conditions underlying the `stop_at_phase_*` stopping conditions

**Comment by Debraheem** [comment]
> wrong path for the star_ptr information, it should be
> `$MESA_DIR/star_data/public/star_data_*.inc`
> as mentioned in the star info section earlier

I can't find the location of the wrong path, perhaps this has already been fixed!

**Comment by BucheleL** [comment]
@Debraheem I still see old path in line 179 of `extending_mesa.rst` in #655.
