### ISSUE TITLE
MESA SDK website not reachable

### ISSUE THREAD

**Issue by Daniel-Pauli** [MESAHub/mesa#675]
Hi all,

I wanted to install and test the latest MESA version (mesa-r24.03.1). When I wanted to download the MESA SDK I am send to this webpage "http://user.astro.wisc.edu/~townsend/static.php?ref=mesasdk" but the side cannot be loaded and give the following error:
SQLSTATE[HY000] [2002] No route to host

I also tried googling to get to the MESA SDK website and with another PC, but with the similar result, so I guess it is a problem from the website provider. 

If you need more information, please let me know.

Cheers,
Daniel

**Comment by orlox** [comment]
In case the official website is down, you can always find the SDKs in zenodo. Although sometimes they might lag behind with the latest version.

Here you have them for Linux:
https://zenodo.org/records/10624843

And here for macOS:
https://zenodo.org/records/10624933

**Comment by Debraheem** [comment]
the website is back online.
