### ISSUE TITLE
ok, i have storm os gnome arch linux. need help with driver issue. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [MESAHub/mesa#698]
i would remove bnvidia, but then my computer ends up havign issues. 

but, i need amd. 

my machine is a legio ngo handheld. a default amd machine. 

how do i switch it from from nvidia to amd?

im trying to install a pc game. but, i cnat due to it being nvidia default driver. 

i have mesa. but, its not show\ing up in pacman -Qet list. 

which means there is a conflict. 

how to solve this driver issue?

**Comment by evbauer** [comment]
Hello! It looks like you may have found your way to the wrong mesa repository. This repo is for the stellar evolution simulation software Modules for Experiments in Stellar Astrophysics (MESA).

Best of luck solving your driver issue!
