### ISSUE TITLE
i1p permission denied

### ISSUE THREAD

**Issue by PLoren-Aguilar** [MESAHub/mesa#734]
When trying to install MESA in a Ubuntu terminal (inside a Windows machine), I get the following error message:

/home/me/mesa-r24.03.1/const
building const package.
. /install: line 40:
/i1p: Permission denied

I have tried to fix it in several ways, but nothing seems to work.

Any help would be greatly appreciated.

Kind regards,

Pablo

**Comment by pmocz** [comment]
Please feel free to reach out to me if you are still having trouble with installation. I am closing this issue here as it's related to setting permissions inside your environment, and not changes to be made to the mesa code.
