### ISSUE TITLE
Fix namespace pollution by num module

### ISSUE THREAD

**Issue by rhdtownsend** [MESAHub/mesa#741]
The num module currently re-exports a number of variables defined in other modules (e.g., const). This is bad practice, and should be an easy fix.

**Comment by pmocz** [comment]
@rhdtownsend could you give some examples and where to find them in the source?

**Comment by rhdtownsend** [comment]
Sure -- if you take a look in num/public/num_lib.f, you'll see there are no private/public statements before the contains statement. This means that all of the symbols e.g. from const_def are re-exported by num. 

What we should have, before the contains statement, is

private
public :: func1
public :: func2

...where func1, func2, etc are the names of the routines defined in num_lib.
