### ISSUE TITLE
History value "Lnuc" is confusing (and maybe subtracting photodisintegrations twice)

### ISSUE THREAD

**Issue by simonguichandut** [MESAHub/mesa#754]
We recently found a situation where `log_Lnuc` in the history file went to -99 (meaning the non-log value is negative (?)), despite ongoing burning. A different quantity, `power_nuc_burn`, stays positive.

Looking through the code, it is a bit confusing what these quantities should mean.  Here's the column descriptions:
https://github.com/MESAHub/mesa/blob/ea1ca9b16f3f1e5424df012f8714e8e3807cf884/star/defaults/history_columns.list#L239-L243

My reading of these is that `log_power_nuc_burn` and `log_Lnuc` should be the same. Both are total burning power excluding photodisintegrations.  But the actual definition of `log_Lnuc` is:
https://github.com/MESAHub/mesa/blob/ea1ca9b16f3f1e5424df012f8714e8e3807cf884/star/private/history.f90#L2228-L2230

If `power_nuc_burn` already excludes photodisintegrations, then this subtraction removes it an extra time (which could explain the -99 we were finding).

Then we go to the definition of `power_nuc_burn`:
https://github.com/MESAHub/mesa/blob/ea1ca9b16f3f1e5424df012f8714e8e3807cf884/star/private/report.f90#L95-L102
It seems to simply be $\int \epsilon_{\rm nuc}dm$. Does $\epsilon_{\rm nuc}$ include or exclude photodisintegrations?

Finally, adding to the confusion, there's this "ghost" history value (not listed in `history_columns.list`):
https://github.com/MESAHub/mesa/blob/ea1ca9b16f3f1e5424df012f8714e8e3807cf884/star/private/history.f90#L2860-L2861
Notice this **lg**_Lnuc instead of **log**. This one does not subtract the photodisintegrations.

**Comment by Debraheem** [comment]
Hello, thanks for raising this! To clarify:

 log_Lnuc  = log(LH + LHe + LZ), and does not in include photodisintegrations, hence the photodisintegrations are subtracted. There does not appear to be any double counting as `s% power_nuc_burn` (calculated from eps_nuc) includes photodisintegration, and therefore to remove it, it must be subtracted as is done in ` case(h_log_Lnuc)`.
 
You are correct that when `Lnuc` becomes negative, `log_Lnuc` becomes undefined .i.e. - 99. 
 
 I think you've also found a documentation bug for `lg_Lnuc`, thanks for catching that! I can add it back into the default history_column.list file with an approprate clarification on its definition. I can also add a clarification for `log_Lnuc`. 
 
Perhaps this motivates providing a non-logarithmic `power_nuc_burn` value to the history_columns.list. Is that what you're looking for?

**Comment by Debraheem** [comment]
you can also use the following to compute it yourself

      !power_h_burn ! total thermal power from PP and CNO, excluding neutrinos (in Lsun units)
      !power_he_burn ! total thermal power from triple-alpha, excluding neutrinos (in Lsun units)
      !power_photo
      !power_z_burn

**Comment by simonguichandut** [comment]
If `power_nuc_burn` does include photodisintegrations (I agree, I think it does), then isn't this incorrect?
https://github.com/MESAHub/mesa/blob/ea1ca9b16f3f1e5424df012f8714e8e3807cf884/star/defaults/history_columns.list#L239

`lg_Lnuc` (with **lg**) represents the same thing as `power_nuc_burn`, so adding it would only make things confusing, I think.

If you want to add a non-logarithmic value it should be `Lnuc` (=`power_nuc_burn` - photodisintegrations), since that is the one that can go negative.

**Comment by Debraheem** [comment]
"! total thermal power from all burning, excluding photodisintegrations " 
This comment is incorrect. It includes photodisintegration, so there is no error, but the documentation needs corrected.

"lg_Lnuc (with lg) represents the same thing as power_nuc_burn, so adding it would only make things confusing, I think."
Yes, agreed. 

"If you want to add a non-logarithmic value it should be Lnuc (=power_nuc_burn - photodisintegrations), since that is the one that can go negative."
Okay.

**Comment by Debraheem** [comment]
It appears that `lg_Lnuc` is the value displayed in the terminal, which could easily be confused with `log_Lnuc`.
```
         case(h_lg_Lnuc)
            val = safe_log10(s% power_nuc_burn)
```

**Comment by simonguichandut** [comment]
Thanks for having a look! Your PR clears up the confusion.
