### ISSUE TITLE
Update pgstar EOS regions to reflect new defaults

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa#91]
A lot of this is hard coded, so we'll need to check right before release to make sure that the EOS region labels actually reflect the EOS that we're using by default.

**Comment by adamjermyn** [comment]
These plots look like they were generated with the EOS plotter, so they're
probably reporting correctly that no EOS wants to lay claim to those
regions.

Does the EOS actually return something in those regions? Is there an
ultimate fallback like the ideal gas law?

Note that the Skye blend locations depend on abar and zbar, so they will
shift around depending on exact composition.



-Adam

**Comment by evbauer** [comment]
It's just returning NaN in those regions!

![iTerm2 zDUN4h eos_plotter](https://user-images.githubusercontent.com/18405113/135128944-017b8da2-b176-4b31-931a-14905ae767a2.png)

**Comment by adamjermyn** [comment]
Ok good! That's what I'd hope it does!

We can introduce a new EOS (ideal ion gas + radiation, perhaps?) that
serves as an ultimate backstop if we need coverage over the whole plane. If
you think that's a good idea I'm happy to add it: it's a pretty
straightforward thing to do with the Skye machinery (though I'd make it
it's own thing to avoid any confusion).

-Adam

**Comment by warrickball** [comment]
> It's just returning NaN in those regions!
> 
> <img src="https://user-images.githubusercontent.com/18405113/135128944-017b8da2-b176-4b31-931a-14905ae767a2.png" height="300px">

I realise the gas pressure probably doesn't contribute much there but I can see the blend (HELM-FreeEOS?) around logT=7.2, logρ=-7.

**Comment by evbauer** [comment]
Oh good point. Maybe the blend is way too narrow there? I can smooth that significantly by setting `logQ_min_FreeEOS_hi = -9.0d0`.
![iTerm2 S2ewd0 eos_regions](https://user-images.githubusercontent.com/18405113/135165385-923bf030-8a39-4db8-a63f-d7372de95ad0.png)
![iTerm2 UR2t72 eos_plotter](https://user-images.githubusercontent.com/18405113/135165405-9bcfbb6c-2868-4549-a02d-87b563946a12.png)

**Comment by warrickball** [comment]
I'll leave it to the EoS experts to judge. I think I've learned that things that are surprising to the untrained eye can be justified or benign. It just surprised me to be able to see the blend in something like the gas pressure.
